// const textData = {
//   0: "Menu Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc,",
//   1: "1Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc,",
//   2: "2Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc,",
//   3: "3Lorem ipsum dolor sit amet, , na ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc,",
//   4: "4Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc,",
//   5: "3Lorem ip ultricies nec,  aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna.",
//   6: [
//     "lOREM Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. ",
//     "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nul ",
//   ],
//   7: [
//     "ALorem ipsum dolor sit amet, .nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate ",
//     "BLorem ipsum dolor sit amet, .nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate ",
//   ],
//   8: "8justo.   Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc,",
//   9: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ",
//   10: [
//     "1Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum ",
//     "2Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum ",
//     "3Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum ",
//   ],
//   11: "11Lorem     montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus",
//   12: [
//     "CLAVELorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum ",
//     "1111Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum ",
//     "222Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum ",
//     "333Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum ",
//   ],
//   13: [
//     "ALorem Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum ",
//     "BLorem Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum ",
//   ],
//   //   14: "13Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc,",
// };
// const titlesData = {
//   0: "Title0",
//   1: "Title1",
//   2: "Title2Contenido",
//   3: "Title3",
//   4: "Title4",
//   5: "Title5",
//   6: ["Title6A", "Title6B"],
//   7: ["Title7A", "Title7B"],
//   8: "Title8",
//   9: "Title9",
//   10: "Title10",
//   11: "Title11",
//   12: "Title12",
//   13: "Title13",
//   //   14: "Title14",
// };
// const layoutData = {
//   0: "Alayout",
//   1: "Blayout",
//   2: "Clayout",
//   3: "Dlayout",
//   4: "Elayout",
//   5: "Flayout",
//   6: "Glayout",
//   7: "Hlayout",
//   8: "Ilayout",
//   9: "Jlayout",
//   10: "Klayout",
//   11: "Llayout",
//   12: "Mlayout",
//   13: "Nlayout",
//   //   14: "Wlayout",
// };
// const popUpData = {
//   0: "",
//   1: "",
//   2: "",
//   3: [
//     {
//       title: "Titulo del modal000DDD",
//       typeofContent: "image",
//       contentModal: "layOutD.jpg",
//       buttonName: "IR1",
//     },
//     {
//       title: "Titulo del modal1111DDD",
//       typeofContent: "text",
//       contentModal:
//         "1111DDDDLorem del MODAL ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum",
//       buttonName: "IR2",
//     },
//   ],
//   4: "",
//   5: "",
//   6: [
//     {
//       title: "",
//       typeofContent: "text",
//       contentModal:
//         "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum GGGGLorem del MODAL ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum",
//       buttonName: "LOREM IPSUM DOLOR SIT AMELOREM IPSUM DOLOR SIT AME",
//     },
//   ],
//   7: [
//     {
//       title: "TITULO1",
//       typeofContent: "image",
//       contentModal: "layOutD.jpg",
//       buttonName: "LOREM IPSUM DOLOR SIT AMELOREM IPSUM DOLOR SIT AME",
//     },
//     {
//       title: "TITULO2",
//       typeofContent: "image",
//       contentModal: "layOutD.jpg",
//       buttonName: "LOREM IPSUM DOLOR SIT AMELOREM IPSUM DOLOR SIT AME",
//     },
//     {
//       title: "TITULO3",
//       typeofContent: "image",
//       contentModal: "layOutD.jpg",
//       buttonName: "LOREM IPSUM DOLOR SIT AMELOREM IPSUM DOLOR SIT AME",
//     },
//     {
//       title: "TITULO4",
//       typeofContent: "image",
//       contentModal: "layOutD.jpg",
//       buttonName: "LOREM IPSUM DOLOR SIT AMELOREM IPSUM DOLOR SIT AME",
//     },
//     {
//       title: "TITULO5",
//       typeofContent: "image",
//       contentModal: "layOutD.jpg",
//       buttonName: "LOREM IPSUM DOLOR SIT AMELOREM IPSUM DOLOR SIT AME",
//     },
//     {
//       title: "TITULO6",
//       typeofContent: "image",
//       contentModal: "layOutD.jpg",
//       buttonName: "LOREM IPSUM DOLOR SIT AMELOREM IPSUM DOLOR SIT AME",
//     },
//     {
//       title: "TITULO7",
//       typeofContent: "image",
//       contentModal: "layOutD.jpg",
//       buttonName: "LOREM IPSUM DOLOR SIT AMELOREM IPSUM DOLOR SIT AME",
//     },
//     {
//       title: "TITULO8",
//       typeofContent: "image",
//       contentModal: "layOutD.jpg",
//       buttonName: "LOREM IPSUM DOLOR SIT AMELOREM IPSUM DOLOR SIT AME",
//     },
//     {
//       title: "TITULO9",
//       typeofContent: "image",
//       contentModal: "layOutD.jpg",
//       buttonName: "LOREM IPSUM DOLOR SIT AMELOREM IPSUM DOLOR SIT AME",
//     },
//     {
//       title: "TITULO10",
//       typeofContent: "image",
//       contentModal: "layOutD.jpg",
//       buttonName: "LOREM IPSUM DOLOR SIT AMELOREM IPSUM DOLOR SIT AME",
//     },
//   ],
//   8: "",
//   9: "",
//   10: "",
//   11: [
//     {
//       title: "TITULO1",
//       typeofContent: "image",
//       contentModal: "layOutD.jpg",
//       buttonName: "LOREM IPSUM DOLOR SIT AMELOREM IPSUM DOLOR SIT AME",
//     },
//     {
//       title: "TITULO2",
//       typeofContent: "image",
//       contentModal: "layOutD.jpg",
//       buttonName: "LOREM IPSUM DOLOR SIT AMELOREM IPSUM DOLOR SIT AME",
//     },
//     {
//       title: "TITULO3",
//       typeofContent: "image",
//       contentModal: "layOutD.jpg",
//       buttonName: "LOREM IPSUM DOLOR SIT AMELOREM IPSUM DOLOR SIT AME",
//     },
//     {
//       title: "TITULO4",
//       typeofContent: "image",
//       contentModal: "layOutD.jpg",
//       buttonName: "LOREM IPSUM DOLOR SIT AMELOREM IPSUM DOLOR SIT AME",
//     },
//     {
//       title: "TITULO5",
//       typeofContent: "image",
//       contentModal: "layOutD.jpg",
//       buttonName: "LOREM IPSUM DOLOR SIT AMELOREM IPSUM DOLOR SIT AME",
//     },
//   ],
//   12: "",
//   13: [
//     {
//       title: "Titulo del modal000",
//       typeofContent: "image",
//       contentModal: "layOutD.jpg",
//       buttonName: "LOREM IPSUM DOLOR SIT AMELOREM IPSUM DOLOR SIT AME",
//     },
//     {
//       title: "Titulo del modal1111",
//       typeofContent: "text",
//       contentModal:
//         "1111Lorem del MODAL ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum",
//       buttonName: "LOREM IPSUM DOLOR SIT AMELOREM IPSUM DOLOR SIT AME",
//     },
//   ],
//   //   14: [
//   //     {
//   //       title: "Titulo del modal000DDD",
//   //       typeofContent: "image",
//   //       contentModal: "layOutD.jpg",
//   //       buttonName: "IR1",
//   //     },
//   //     {
//   //       title: "Titulo del modal1111DDD",
//   //       typeofContent: "text",
//   //       contentModal:
//   //         "1111DDDDLorem del MODAL ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum",
//   //       buttonName: "IR2",
//   //     },
//   //   ],
// };
// const imagesData = {
//   0: "",
//   1: "",
//   2: "",
//   3: "layOutD.jpg",
//   4: "layOutD.jpg",
//   5: "layOutD.jpg",
//   6: "",
//   7: "",
//   8: ["layOutD.jpg", "layOutD.jpg"],
//   9: ["layOutD.jpg", "layOutE.jpg", "layOutF.jpeg", "layOutD.jpg"],
//   10: "layOutD.jpg",
//   11: "",
//   12: "layOutD.jpg",
//   13: "",
//   //   14: "",
// };

const textData = {
  0: "mmmm",
  1: "Viceministerio de Educación Superior de Formación Profesional Dirección General de Formación de Maestros <br> Unidad Especializada de Formación Continua - UNEFCO <br> Equipo de redacción y dirección: <br> Fundación Ayuda en Acción ProggettoMondo <br> Unidad Especializada de Formación Continua - UNEFCO <br>Diseño Recurso Digital Iris OrtegaRodrigo Coronel <br> www.minedu.gob.bo <br> http://unefco.minedu.gob.bo/ <br> Bolivia, marzo, 2024 <br>",
  2: "Presiona los botones para navegar en el libro",
  3: "<br> El Plan de Formación para maestras y maestros es una modalidad de aprendizaje, compuesta por cursos cortos, desarrollada por el Ministerio de Educación a través de la Unidad Especializada de Formación Continua (UNEFCO) para profundizar y fortalecer habilidades y capacidades en la labor educativa, con un enfoque en la mejora de las prácticas y procesos formativos. Su propósito, de acuerdo con la Ley de Educación N° 070 “Avelino Siñani – Elizardo Pérez”, es trabajar por la universalización del Modelo Educativo Sociocomunitario Productivo, en atención a los diferentes niveles y áreas temáticas, con relevancia cultural y lingüística. <br> <br>Las prácticas restaurativas se han venido consolidando como una ciencia social emergente desde aproximadamente el 2013, época en la cual se estudian las acciones individuales y colectivas dirigidas hacia tres objetivos: el fortalecimiento comunitario, la resolución pacífica de conflictos y la reparación del daño cuando se produce. Se definen las mismas como respuestas no punitivas orientadas a la reparación del daño, potenciar las relaciones interpersonales, fortalecer la resolución de los conflictos y desarrollar soluciones que incluyan a todas las personas involucradas en un daño; tomando en cuenta que el manejo restaurativo de los afectos en el aula mejora la capacidad para el aprendizaje y la resiliencia. <br> <br>Los cuadernos del ciclo formativo: “PRÁCTICAS RESTAURATIVAS PARA LA RESOLUCIÓN DE CONFLICTOS Y UNA VIDA LIBRE DE VIOLENCIA”, nos invitan a replantearnos la manera en que enfrentamos conflictos, desafiando los paradigmas arraigados de confrontación y castigo. A medida que nos sumergimos en las profundidades de las prácticas restaurativas, descubrimos su capacidad no solo para restaurar el daño causado por los conflictos, sino también para fortalecer nuestros lazos comunitarios y fomentar un clima de confianza y respeto mutuo. <br><br>Este ciclo cuenta con tres cursos, en el Primer Curso, se aborda la parte normativa, lo que es y no es conflicto para luego introducir al enfoque restaurativo; en el Segundo Curso se aborda las condiciones básicas para una comunidad educativa restaurativa y los roles de sus miembros; y en el Tercer Curso presentamos una caja de herramientas práctica para la aplicación en el quehacer educativo. <br><br>Jorge Galindo Villa Castro COORDINADOR GENERAL – UNEFCO",
  4: "<br><br><b> OBJETIVO HOLÍSTICO DEL CICLO</b>  <br><br>Desarrollamos procesos de análisis y reflexión sobre los principios del enfoque restaurativo, en la incorporación de las prácticas restaurativas en la interacción educativa cotidiana, a través de las decisiones de promoción de una convivencia pacífica y libre de violencia educativa, para que maestras y maestros sean los principales actores en la resolución de conflictos. <br><br><br> <b> OBJETIVO HOLÍSTICO DEL CURSO</b> <br><br>Reflexionamos sobre las ventajas de la aplicación del enfoque restaurativo, a través de las prácticas restaurativas para la resolución de conflictos, como modelo facilitador en las intervenciones restaurativas para la construcción de una comunidad educativa libre de violencia y con cultura restaurativa.",
  5: "Tema 1",
  6: "<br> Cada sistema educativo opera dentro de un conjunto de normativas diseñadas para proteger los derechos de los estudiantes y fomentar un ambiente seguro. En esta actividad, exploraremos los principales instrumentos legales a nivel nacional e internacional que prohíben el castigo físico y promueven una convivencia pacífica.",
  7: [
    "<br>  Como maestras y maestros es fundamental conocer las normas de protección y prevención referidas a la resolución de conflictos para una vida sin violencia; porque son recursos importantes que nos comprometen y vuelven conscientes de nuestros derechos y obligaciones, además que nos orientan en el abordaje y tratamiento de esta temática dentro de nuestra práctica educativa. <br>",
    "<b>  CONVENCIÓN DE LOS DERECHOS DE LA NIÑEZ Y LA ADOLESCENCIA</b><br><br>La normativa internacional establece criterios de protección frente a situaciones de conflicto en unidades educativas. <br> Estos artículos buscan proteger los derechos y el bienestar de los niños, niñas y adolescentes en contextos escolares, asegurando un ambiente seguro y propicio para su desarrollo integral. <br> Es fundamental que las unidades educativas apliquen estas disposiciones para garantizar una educación inclusiva y libre de violencia. <br><br>",
  ],
  8: [
    "A nivel nacional, la niñez y adolescencia con base a diferentes normativas son protegidas en su integridad física, psicológica y sexual; en el sistema educativo.",
    "Maestras y maestros conocen la importancia de cuidar el interés superior de la niñez y adolescencia que guía su actuar ante una situación de violencia de no pares en el sistema educativo, por un lado; y por otro lado pueden actuar conforme a la normativa boliviana que respalda los derechos de sus estudiantes.",
  ],
  9: [
    "La normativa emitida por el Ministerio de Educación: R.M. N° 001/2018 Subsistema de Educación Regular, Normas generales para la gestión educativa y escolar; R. M. N° 1204/2018 Violencia entre pares o acoso escolar, promulgado en noviembre del 2018; R. M. N° 0001/2024 Normas generales para la gestión educativa 2024 del Subsistema de Educación Regular; R. M. N° 864/2019",
    "Protocolo de prevención, actuación y denuncia en casos de violencia física, psicológica y sexual en unidades educativas y centros de educación especial promulgada en agosto del 2019, protege los derechos y garantías de la niñez y la adolescencia en las unidades educativas.",
  ],
  10: "<br> Este contenido, puede ser transmitido también a sus estudiantes, para que puedan comprender la importancia de sus derechos y su rol en el ejercicio; reconociéndose como sujetas y sujetos de derechos, que son parte de la protección y participación para la elaboración del Plan de Convivencia Pacífica y Armónica, y generar corresponsabilidad en las Rutas de Referencia y Contra referencia. <br><br> Formamos grupos de trabajo, se da lectura al caso de Lucy y Ana. Posteriormente intercambiamos opiniones, guiándonos con las siguientes preguntas:",
  11: "En esta actividad, identificarás los conflictos más comunes en el aula y completarás una tabla con estrategias preventivas. La plantilla te permitirá registrar factores de riesgo, posibles intervenciones y buenas prácticas para promover la convivencia pacífica.",
  12: "Tema 2",
  13: "El conflicto es una parte natural de la convivencia, pero su manejo puede determinar el clima escolar. A través de esta actividad, identificaremos las principales fuentes de conflicto en el aula, analizaremos cómo se abordan actualmente y propondremos estrategias para transformarlos en oportunidades de aprendizaje y crecimiento.",
  14: "Avanza con las flechas para revisar más información",
  15: [
    "La diferencia se establece entre problema y conflicto, dando a conocer que el problema es totalmente individual relacionado al sujeto, teniendo en cuenta que puede haber involucrados al problema afectando a demás personas a diferencia del conflicto debe existir dos o más personas que estén implicados, en efecto debe darse la resolución para ambas partes, en el cual debe existir conformidad",
    "<br>Habitualmente, la palabra “conflicto” lleva asociada connotaciones peyorativas. Seguramente esto es debido a que solemos identificarla con “violencia”. Es cierto que en ocasiones la violencia es la negación del conflicto, en la medida que pretende eliminar al diferente, negar su humanidad e imponer una falsa solución por la fuerza”. (Progettomondo.Mlal, EDUCO, FUDEP, 2018)",
  ],
  16: "El conflicto no es ajeno al ámbito educativo y el reto es aprender a construir a partir de él, convivir con el conflicto y estar preparados para educar para la búsqueda de una solución, ya que este debe entenderse como una oportunidad de cambio, de crecimiento y de aprendizaje. <br>En general, el conflicto se puede entender como una oportunidad de cambio y transformación por la comunidad. <br> En este sentido, los conflictos son inevitables, a veces impredecibles, pero la gran mayoría de ellos se pueden administrar y resolver. <br> En consecuencia, los conflictos surgen y se expresan de diferente manera, por motivos diversos y con distinta intensidad entre las personas. <br> Depende mucho del lugar desde donde uno ve el conflicto, lo que no significa la imposibilidad de llegar a acuerdos y soluciones a través del diálogo",
  17: "El conflicto es una parte inherente a la vida humana y surge de desacuerdos entre dos o más personas, pudiendo escalar hasta la violencia si no se gestiona adecuadamente. Es un fenómeno visible, que a menudo refleja problemas más profundos y puede tener impactos tanto positivos como negativos en la convivencia. Aunque algunos conflictos buscan dañar, también representan oportunidades para el aprendizaje y el cambio. La clave no es evitarlos, sino aprender a enfrentarlos de manera constructiva, ya que seguirán surgiendo en la medida en que interactuamos y evolucionamos.",
  18: "Avanza con las flechas para revisar más información",
  19: "Los conflictos entre estudiantes son situaciones de tensión, desacuerdo o enfrentamiento que pueden surgir en el entorno escolar. Estos conflictos pueden afectar la convivencia, el aprendizaje y el bienestar de los estudiantes. Algunos ejemplos de conflictos entre estudiantes incluyen:",
  20: "Los conflictos en estudiantes de primaria y secundaria pueden variar debido a las diferencias en su desarrollo cognitivo, emocional y social. A continuación, se tienen algunas de las diferencias clave:",
  21: "Avanza con las flechas para revisar más información",
  22: "Los factores de riesgo en la unidad educativa se refieren a las condiciones o circunstancias que aumentan la probabilidad de resultados negativos, como problemas de conducta, problemas de salud física o mental, bajo rendimiento académico, delincuencia o abuso de sustancias. Algunos ejemplos de factores de riesgo en el contexto educativo incluyen la pobreza, la depresión en los padres y madres, el estrés en los padres y madres, los conflictos familiares o la violencia, el abandono emocional y el consumo de alcohol o drogas durante el embarazo. Estos factores pueden afectar el desarrollo y el bienestar de las y los estudiantes, destacando la importancia de abordarlos para promover un entorno educativo saludable propicio para el aprendizaje. (Observatorio de la educación peruana, 2021) <br> <br> Para abordar estos factores, es esencial implementar medidas preventivas que promuevan el desarrollo y el bienestar de los estudiantes. Estas medidas pueden incluir programas de aprendizaje social y emocional, programas de tutoría, iniciativas de participación familiar y asociaciones comunitarias. <br>Además, es importante crear un clima escolar positivo que fomente el respeto, la inclusión y la colaboración, así como proporcionar recursos y apoyo adecuados a los estudiantes y las familias.",
  23: "La violencia juvenil está influenciada por diversos factores de riesgo que operan en diferentes niveles. A nivel individual, la falta de empatía, la baja autoestima, la impulsividad y el consumo de sustancias pueden aumentar la propensión a conductas violentas. En el ámbito familiar, la crianza autoritaria, la violencia doméstica y la falta de comunicación pueden contribuir a estos comportamientos. En el entorno escolar, normas poco claras, la falta de atención a la diversidad y la ausencia de metodologías adecuadas generan un clima propicio para la violencia. Además, la comunidad juega un papel clave, ya que la pobreza, la falta de oportunidades económicas y la baja participación social pueden agravar la situación. Comprender estos factores es esencial para diseñar estrategias efectivas de prevención y atención.",
  24: "El Código Niña, Niño y Adolescente en su artículo 150 menciona la protección contra la violencia en el sistema educativo: “La protección a la vida y la integridad física y psicológica de los miembros de la comunidad educativa, implica la prevención, atención y sanción de la violencia ejercida en el Sistema Educativo del Estado Plurinacional de Bolivia, con la finalidad de consolidar la convivencia pacífica y armónica, la cultura de paz, tolerancia y justicia, en el marco del Vivir Bien, el buen trato, la solidaridad , el respeto, la intraculturalidad, la interculturalidad y la no discriminación entre sus miembros” (Estado Plurinacional de Bolivia, 2014). Haciendo énfasis en la importancia de la prevención. <br> <br> En el artículo 151 del Código, menciona siete tipos de violencia: <br>Violencia entre pares <br> Violencia entre no pares<br>Violencia Verbal<br>Discriminación en el sistema educativo<br>Violencia en Razón de Género<br>Violencia en Razón de la Situación Económica<br>Violencia Cibernética en el Sistema Educativo",
  25: "La consideración de estos tipos de violencia, permiten establecer medidas de prevención, entre ellas: <br><br>  a. Elaboración de Planes de Convivencia Pacífica y Armónica. <br>b. Adoptación de procedimientos alternativos para resolver conflictos. <br>c. Programar actividades intencionadas para promover una cultura de buen trato y prevención de violencias. <br><br>Así mismo, el protocolo de prevención, actuación y denuncia, define la violencia en el ámbito educativo en violencia física, psicológica y sexual en unidades educativas y centros de educación especial:",
  26: [
    "La violencia se manifiesta de diversas formas y afecta la vida de las personas, impactando su bienestar emocional, físico y social. Comprender sus distintos tipos es fundamental para identificarla y prevenirla en cualquier contexto, especialmente en el ámbito educativo y comunitario.",
    "No todas las formas de violencia son evidentes o directas. En muchos casos, la omisión y la falta de protección pueden causar tanto daño como una agresión explícita. Por otro lado, la violencia sexual constituye una de las formas más graves de vulneración de derechos, ya que atenta contra la integridad, la dignidad y la seguridad de la persona. ",
  ],
  27: "Para profundizar en la importancia de la protección de la niñez y adolescencia, te invitamos a leer artículos de la Ley N° 548. En ellos encontrarás las bases legales que sustentan la prevención y atención de la violencia en sus diferentes formas.",
  28: "Avanza con las flechas para revisar más información",
  29: "<br> “Las prácticas restaurativas son herramientas que permiten generar relaciones armoniosas y sentido de comunidad, desarrollar habilidades para la vida, expresar emociones y resolver conflictos promoviendo que las personas asuman sus responsabilidades y las consecuencias de su conducta, intentando restaurar la relación con el otro” (hommes, 2018; terres des hommes, 2014; terres des hommes, 2014). <br>  <br> En este sentido a continuación se presenta un cuadro resumido de las prácticas restaurativas; las primeras tres son aplicadas sobre todo de manera preventiva y las siguientes dos son cuando ya fue dada la violencia o conflicto: <br><br>Por ello, es importante tener presente que, para cada violencia, existe una práctica para abordar, resolver y restaurar.",
  30: "Para construir una convivencia pacífica y resolver conflictos de manera efectiva, las prácticas restaurativas ofrecen diversas herramientas que fomentan el diálogo, la empatía y la responsabilidad. Estas estrategias permiten que las personas involucradas en un conflicto expresen sus emociones, reparen el daño causado y fortalezcan sus relaciones.",
  31: [
    "La violencia en el sistema educativo puede manifestarse de diversas formas, afectando la convivencia y el bienestar de la comunidad escolar. Sin embargo, a través de un enfoque restaurativo, es posible transformar estas situaciones en oportunidades de aprendizaje y fortalecimiento de relaciones.",
    "A continuación, presentamos una tabla que asocia los tipos de violencia más comunes en el ámbito educativo con prácticas restaurativas sugeridas, permitiendo una intervención efectiva y adaptada a cada contexto. Estas estrategias fomentan el diálogo, la responsabilidad y la reparación del daño, promoviendo un ambiente de respeto y confianza en el entorno escolar.",
  ],
  32: "El Código Niña, Niño y Adolescente menciona la participación de la niñez y la adolescencia como un principio y un derecho, a través del cual pueden involucrarse en la vida familiar, comunitaria, social, escolar y otros espacios de interés; para ser escuchadas/os y tomados en cuenta. <br> <br> Por su parte la Ley No. 070 consolida un espacio de protagonismo a los gobiernos estudiantiles para ser representativos de sus pares y que logran consolidarse en las unidades educativas. <br> <br> La resolución de conflictos no solo es asunto del plantel docente o administrativo, sino también de los otros actores de la comunidad educativa; entre ellos; las y los estudiantes. <br> <br> Al hacerlos parte de la resolución de conflictos; se les reconoce su rol de sujetas y sujetos de derechos; con capacidades de ser y actuar; también de poder decidir y aportar para cambiar una situación que se da en su entorno más inmediato que es la unidad educativa. Por tanto, adoptan un rol protagónico, porque no es ajeno a los conflictos y situaciones de violencia que pasa en su contexto. <br> <br>Es por eso, que es importante involucrarlos en la solución y para ello, también se debe desarrollar capacidades de escucha activa, diálogo, empatía, incluso hasta de mediación con sus pares, lo cual permite desarrollar en ellas y ellos, la corresponsabilidad.",
  33: "La diferencia se establece entre problema y conflicto, dando a conocer que el problema es totalmente individual relacionado al sujeto, teniendo en cuenta que puede haber involucrados al problema afectando a demás personas a diferencia del conflicto debe existir dos o más personas que estén implicados, en efecto debe darse la resolución para ambas partes, en el cual debe existir conformidad",
  34: "Tema 3",
  35: "Las prácticas restaurativas buscan fortalecer la comunidad educativa mediante la empatía, la comunicación efectiva y la reparación del daño. En esta actividad, reflexionaremos sobre experiencias personales relacionadas con conflictos y exploraremos cómo un enfoque restaurativo puede mejorar las relaciones interpersonales y el ambiente en el aula.",
  36: [
    "El enfoque de Derechos Humanos se constituye en un marco conceptual que busca contribuir al proceso de desarrollo humano, además de orientar las acciones necesarias para dar cumplimiento a los derechos de las personas. Considera una serie de principios y ejes rectores que promueven la realización de todos los derechos como indivisibles e irrenunciables, articulados en tres grupos: derechos de supervivencia y desarrollo, derechos de protección, derechos de participación.Tomando en cuenta el ámbito normativo, este enfoque está basado en las disposiciones y estándares contenidos de los diferentes instrumentos internacionales de derechos humanos. Son el referente y fin último de las políticas públicas y estas, a su vez, son el instrumento o medio más idóneo para su realización. implica realizar transformaciones sociales a partir del reconocimiento y análisis de las desigualdades que se encuentran en el centro de los problemas del desarrollo, a fin de corregir prácticas discriminatorias y el desigual reparto del poder que obstaculizan un desarrollo igual para todas y todos.",
  ],
  37: "El enfoque restaurativo tiende a mirar la resolución de problemas de manera colaborativa, brindando la oportunidad a las personas involucradas víctima y ofensora; en elaborar un plan para reparar daño causado. En el proceso, está involucradas ambas partes, porque permite generar empatía hacia la parte ofensora, comprendiendo la importancia de no repetir el daño; atendiendo así las necesidades de todas las personas involiucradas y restituyendo de esta forma el derecho a la víctima. <br> <br> Vale decir, “... anima a la parte ofensora a responsabilizarse de sus acciones y del daño causado, a comprender las causas y efectos de su comportamiento en los otros; y a ofrecer soluciones que reparen el daño para merecer su reintegración en la comunidad, desde el reconocimiento que se juzgan los hechos y no al autor del delito” (Schmitz, El enfoque restaurativo para la construcción de paz desde la escuela, 2022). Por tanto, el enfoque restaurativo, es un camino para la construcción de la convivencia pacífica.",
  38: "Históricamente el conflicto ha estado asociado a la violencia, al malestar social, al desequilibrio y al caos, y las formas de su resolución estaban basadas en los esfuerzos por su eliminación y/o neutralización. Los caminos y medios usados con más frecuencia estaban signados por la represión, en el sentido más amplio y el castigo. <br> A este, se le relaciona con el enfoque punitivo, más aún cuando hasta hace algunos años, era permitido el disciplinamiento, como una práctica social naturalizada y aceptada por la misma comunidad educativa. <br> <br> En los tiempos actuales se observa la emergencia de diferentes movimientos y colectivos sociales, que interpelan las normas, costumbres y todas las formas de control social existentes, por lo cual, frente a la resistencia de las fuerzas conservadoras, los conflictos afloran con fuerza de distinta intensidad. <br> Por otra parte, se coincide en que las diferentes formas de violencia se están manifestando con mayor intensidad en el entramado social, afectando la vida cotidiana de amplios sectores sociales. Es decir, nos encontramos frente a una compleja trama social en la que los conflictos irrumpen con diferente fuerza e intensidad. (Progettomondo.Mlal, EDUCO, FUDEP, 2018). <br> Este enfoque restaurativo; es donde se ve de otra forma la solución de conflictos, violencia y reparación de daño.",
  39: "La disciplina punitiva, implica recurrir al castigo para el cumplimiento de las reglas y normas de comportamiento, puede ser dañina e injusta. En este sentido, las prácticas restaurativas ofrecen soluciones esperanzadoras. (Progettomondo.Mlal, EDUCO, FUDEP, 2018) <br> <br> Investigaciones realizadas principalmente en países como Nueva Zelanda, Australia y Canadá́, donde las prácticas restaurativas se implementan en escuelas y colegios desde varios años, muestran que el enfoque restaurativo ha transformado las actitudes y comportamientos de sus estudiantes, así́ como ha construido comunidades educativas fuertes y saludables, en las cuales los índices de violencia se han reducido significativamente. <br> <br> Las prácticas restaurativas han demostrado que la mejor forma para resolver los conflictos es alentar a las/os estudiantes para reflexionar sobre lo que sucede, asumir la responsabilidad de sus acciones y elaborar planes para reparar daños. (Schmitz, 2018) <br> <br> La creciente conciencia de que los castigos, como la suspensión y expulsión, solo agravan los problemas en vez de solucionarlos: más violencia, bajo rendimiento académico, apatía de los padres/madres, ha llevado a educadores, maestras y maestros y directores a explorar de forma consciente e inconsciente las prácticas restaurativas como alternativa para crear entornos seguros de aprendizaje y apoyo. (Schmitz, 2018)",
  40: [
    "<b>Enfoque punitivo dentro del sistema de disciplina y convivencia educativa  </b> <br><br> El comportamiento indebido, de parte del estudiante, es considerado como un acto que va en contra de la unidad educativa. Es una idea bastante abstracta. <br> <br>Para este tipo de administración de disciplina educativa quien comete un acto indebido debe recibir una sanción por el daño ocasionado. Es el pensamiento del “ojo por ojo, diente por diente <br>",
    "<b>Enfoque restaurativo dentro del sistema de disciplina y convivencia educativa </b><br><br>El comportamiento indebido, por parte del estudiante, es un acto que va en contra de otra persona u otras personas, miembros de la comunidad educativa por lo que provoca una ruptura de las relaciones, afectando la convivencia en la unidad educativa. <br> <br> Este enfoque considera que, para la convivencia, es de vital importancia asumir responsabilidad, reparar los daños causados, restaurar el clima de convivencia que se vio afectado por la conducta indebida y siempre que se pueda lograr la reconciliación entre las partes en conflicto. <br><br> ",
  ],
  41: [
    "<b>Enfoque punitivo dentro del sistema de disciplina y convivencia educativa </b>  <br> <br> El enfoque punitivo se interesa únicamente por el hecho sucedido: ¿Por qué́ te comportaste de tal manera?, generando un sentimiento de culpa. <br>  Las personas responsables de la disciplina se enfocan en el error cometido: ¿Él o ella lo hizo? <br>  Lo que importa es la mala conducta, nada importa de saber lo que le ha llevado a comportarse de tal o cual manera.<br>",
    "<b> Enfoque restaurativo dentro del sistema de disciplina y convivencia educativa </b> <br><br> Si bien es importante que las personas responsables de la convivencia sepan lo que ha pasado, es fundamental interesarse en conocer por qué y pensar en el futuro.",
  ],
  42: " El enfoque restaurativo en unidades educativas se caracteriza por abordar los conflictos desde un enfoque social, afectivo, pedagógico y de derechos, orientado por los principios de protección integral e interés superior de niños, niñas y adolescentes. <br> <br>  La implementación de Estas prácticas busca mejorar la convivencia escolar al crear vínculos entre los miembros de la comunidad educativa, resolver conflictos a través del diálogo, crear entornos positivos con la participación de toda la comunidad educativa y restaurar las relaciones. Además, se basan en el diálogo restaurativo y en los círculos de diálogo, promoviendo la reparación de los daños causados, asumiendo responsabilidades y fomentando la prevención de situaciones de vulneración. (GOV. CO, 2022) <br> <br> En el contexto escolar se centra en el daño que produce la infracción a la norma, en lugar de en la infracción en sí misma. Esto implica pasar de preguntarse “¿qué norma se ha infringido?, ¿quién debe ser culpado? y ¿de qué manera debemos castigar a la persona infractora?” a preguntarse “¿quién ha sido perjudicado?, ¿quién es responsable de arreglar la situación y reparar?” <br> <br>  Este enfoque ha demostrado ser eficaz en la promoción de relaciones profesionales abiertas, honestas, transparentes y justas, y en la gestión de las relaciones y de los conflictos entre el personal. Además, que es su implementación ha demostrado ser una herramienta efectiva para la organización de la convivencia escolar. (imotiva, 2015)",
  43: "El enfoque restaurativo es una filosofía que se centra en la víctima y la comunidad, y busca reparar el daño causado a través del diálogo y la comprensión del impacto de las acciones del infractor. Esta situación es presente en diversas culturas y busca la transformación y enriquecimiento humano de las partes del proceso y su sanación.",
  44: "Todos y cada uno de quienes conforman la comunidad educativa: estudiantes, maestras, maestros, administrativos, madres y padres de familia, deben y merecen ser valorados como personas, pero sobre todo con la posibilidad de generar ciudadanía y participación protagónica a través de los procesos de toma de decisiones dentro de un aula y escuela. Cuando estudiantes sienten que una decisión que les afecta ha sido tomada de manera justa, confían y cooperan con el mundo adulto, pero sobre todo con maestros y maestras, que tomaron una decisión. Dicho proceso puede revelar la voluntad de una unidad educativa de confiar en el estamento estudiantil, y considerar sus ideas y experiencia o, por el contrario, rechazarlas, sin embargo, dentro de un marco de respeto y argumentación (Progettomondo.Mlal, EDUCO, FUDEP, 2018).",
  45: "En la ventana de la disciplina social, muestra el estilo de autoridad que una persona asume.La ventana de la disciplina social es un concepto que describe cuatro enfoques básicos para mantener las normas sociales y los límites conductuales. Puede ser aplicado al ámbito familiar como en el escolar. Las características que se describen a continuación permiten comprender mejor sus características:",
  46: "El modo en que se ejerce la autoridad en el aula influye directamente en la convivencia, el aprendizaje y el desarrollo socioemocional de los estudiantes. La ventana de la disciplina social nos permite analizar los diferentes estilos de autoridad según el nivel de firmeza, control y apoyo que brindan.",
  47: "Avanza con las flechas para revisar más información",
  48: "La psicología de los afectos, basada en el trabajo del psicólogo americano Silvan Tomkins, nos ayuda a comprender mejor por qué las personas actúan y responden de ciertas maneras, y por qué las prácticas restaurativas funcionan de manera adecuada. De acuerdo con Tomkins, los seres humanos tienen nueve afectos innatos. Todas las personas nacen con estos nueve afectos, que se pueden considerar como la base biológica de nuestras emociones. A medida que se crece, se adquiere nuevos afectos. Cada afecto es sentido dentro de variedad de leve a fuerte.",
  49: "A través de esta actividad, examinarás diferentes tipos de conflictos en el entorno educativo, sus causas y consecuencias. Completarás una plantilla donde clasificarás los conflictos según su impacto y propondrás formas de abordarlos desde un enfoque restaurativo.",
  50: [
    "La construcción de un ambiente educativo basado en el respeto y la convivencia positiva depende de la interacción entre todos los actores de la comunidad. Para ello, es clave fomentar la comunicación efectiva y el diálogo como herramientas para la gestión de conflictos.",
    "Las prácticas restaurativas ofrecen un marco de acción para resolver conflictos de manera justa y participativa. Estas herramientas buscan reparar el daño causado, fortalecer las relaciones y fomentar una convivencia armoniosa.",
  ],
  51: "Bolivariano, I. E. (2023). Institución Educativa Bolivariano. <br>Informe de 2013. (2016). Promover la justicia restaurativa para las niñas, niños y adolescentes. New York, Estados unidos: Oficina del representante Especial del secretario general sobre la violencia contra los niños. <br> Schmitz, J. (2020). Prácticas restaurativas en el ámbito educativo. Ecuador. <br> Candia Moreno, Fernando (Coord). (1999). Diccionario de pedagogía y psicología. Madrid, España: Editorial Cultural. <br> Fernández, I. (2003). Escuela sin violencia: Resolución de conflictos. México: Grupo Editores Alfaomega. <br> San Martín, J. A. (2003). La mediación escolar. Un camino para la gestión del conflicto escolar. Madrid, España. <br> Rodríguez, R. (2005). La acción tutorial para favorecer la convivencia: la disciplina. <br> Educación, M. d. (2022). CICLO: PROMOVIENDO LA CONVIVENCIA PACÍFICA Y ARMÓNICA EN LAS UNIDADES EDUCATIVAS. Bolivia: Comunicación conceptual. <br> Paulero, R. (2021). Conflictos entre maestras y maestros y maestras y maestros y directivos de nivel primario. Representaciones, vivencias, comportamientos y consecuencias en la práctica docente. Revista Latinoamérica de Políticas y administración de la educación, 140-152.",
  52: "UNEFCO. (2022). CICLO: PROMOVIENDO LA CONVIVENCIA PACÍFICA Y ARMÓNICA EN LAS UNIDADES EDUCATIVAS. Tarija, Bolivia: UNEFCO.  <br> Oscar Vasquez. (2018). Guía práctica para desarrollar prácticas restaurativas en las instituciones educativas Basada en la experiencia de la Fundación Terre des hommes en el Perú (2011-2017). Lima, Perú: Pixel Gráfico Impresores S.A.C. <br> Vargas, G. (2019). Factores protectores y afrontamiento de riesgos asociados al uso de sustancias psicoactivas en adolescentes y jóvenes. La Paz, Bolivia: WA-GUI. <br> Terres des hommes. (2014). Auditoría Social de niños, niñas y adolescentes ¿Es tiempo de derechos? Cochabamba, Bolivia: Kipus. <br> Hommes, T. d. (2018). Prevención de la violencia escolar y la convivencia pacífica. Guía práctica para desarrollar prácticas restaurativas en las instituciones educativas. Perú: Pixel Gráfico Impresores S.A.C. <br> Progettomondo.Mlal, EDUCO, FUDEP. (2018). Prácticas restaurativas para la prevención y gestion de conflictos en el ámbito educativo. La Paz, Bolivia: Imprenta Cerro Azul S.R.L. <br> Oscar Vasquez. (2018). Guía práctica para desarrollar prácticas restaurativas en las instituciones educativas Basada en la experiencia de la Fundación Terre des hommes en el Perú (2011-2017). Lima, Perú: Pixel Gráfico Impresores S.A.C. <br> Vargas, G. (2019). Factores protectores y afrontamiento de riesgos asociados al uso de sustancias psicoactivas en adolescentes y jóvenes. La Paz, Bolivia: WA-GUI. <br> Terres des hommes. (2014). Auditoría Social de niños, niñas y adolescentes ¿Es tiempo de derechos? Cochabamba, Bolivia: Kipus. <br> Hommes, T. d. (2018). Prevención de la violencia escolar y la convivencia pacífica. Guía práctica para desarrollar prácticas restaurativas en las instituciones educativas. Perú: Pixel Gráfico Impresores S.A.C. <br> Progettomondo.Mlal, EDUCO, FUDEP. (2018). Prácticas restaurativas para la prevención y gestion de conflictos en el ámbito educativo. La Paz, Bolivia: Imprenta Cerro Azul S.R.L.",
  //   53: "texto a remplazar",

  //   14: "13Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc,",
};
const titlesData = {
  0: "Title0",
  1: "Curso 1: Enfoque restaurativo dentro del sistema educativo",
  2: "Contenido",
  3: "PRESENTACIÓN",
  4: "DATOS GENERALES DEL CUADERNO",
  5: " ",
  6: "Conociendo el Marco Normativo",
  7: ["Base normativa", "Normativa internacional:"],
  8: ["Normativa nacional", "Ley 548 Codigo niño, niña, adolescente"],
  9: [
    "Ministerio de educación",
    "Normativa emitida por el Ministerio de Educación",
  ],
  10: "Protocolo de prevención",
  11: "Estrategias para la Prevención de Conflictos",
  12: " ",
  13: "Reflexionando sobre el Conflicto en el Entorno Educativo",
  14: " ",
  15: "Diferencia entre conflicto y problema",
  16: " ",
  17: "Características del conflicto",
  18: "Conflictos entre personal docente",
  19: "Conflictos entre estudiantes",
  20: "Los conflictos en estudiantes de primaria y secundaria",
  21: " ",
  22: "Factores de riesgo en la unidad educativa",
  23: "Factores de riesgo considerando la violencia juvenil",
  24: "Violencia en el ámbito educativo",
  25: "mmmmm",
  26: ["Glosario violencia", "Violencia por negligencia y violencia sexual"],
  27: "Para profundizar",
  28: " ",
  29: "Para cada tipo de violencia hay una práctica restaurativa",
  30: "Herramientas para la practica restaurativa",
  31: [
    "Tipos de violencia y practicas restaurativas sugeridas",
    "Practicas restaurativas en ámbitos educativos",
  ],
  32: "Protagonismo estudiantil para la resolución de conflictos",
  33: "Diferencia entre conflicto y problema",
  34: " ",
  35: "La importancia del enfoque restaurativo",
  36: [
    "Enfoque de derecho como base para el enfoque restaurativo",
    "Prácticas restaurativas",
  ],
  37: "Enfoque restaurativo",
  38: "Diferencias entre el enfoque restaurativo y punitivo en el ámbito educativo",
  39: "Comparación entre los enfoques punitivo y restaurativo",
  40: "Enfoque punitivo vs. Enfoque restaurativo",
  41: "Enfoque punitivo vs. Enfoque restaurativo",
  42: "Características y principios del enfoque restaurativo",
  43: "Enfoque restaurativo",
  44: "Proceso justo",
  45: "Ventana de la disciplina social",
  46: "Estilos de autoridad en el aula",
  47: "Dialogo restaurativo",
  48: "Los afectos y la brújula de la vergüenza",
  49: "Identificando y analizando el conflicto",
  50: "Glosario",
  51: "Bibliografía",
  52: "Bibliografía",
  //   53: " "

  //   14: "Title14",
};
const layoutData = {
  0: "Alayout",
  1: "Blayout",
  2: "Clayout",
  3: "Blayout",
  4: "Dlayout",
  5: "Elayout",
  6: "Flayout",
  7: "Glayout",
  8: "Hlayout",
  9: "Hlayout",
  10: "Ilayout",
  11: "Flayout",
  12: "Elayout",
  13: "Flayout",
  14: "Jlayout",
  15: "Klayout",
  16: "Dlayout",
  17: "Dlayout",
  18: "Jlayout",
  19: "Dlayout",
  20: "Llayout",
  21: "Jlayout",
  22: "Dlayout",
  23: "Llayout",
  24: "Blayout",
  25: "Ilayout",
  26: "Hlayout",
  27: "Flayout",
  28: "Jlayout",
  29: "Blayout",
  30: "Llayout",
  31: "Glayout",
  32: "Blayout",
  33: "Flayout",
  34: "Elayout",
  35: "Flayout",
  36: "Glayout",
  37: "Dlayout",
  38: "Blayout",
  39: "Blayout",
  40: "Nlayout",
  41: "Nlayout",
  42: "Blayout",
  43: "Llayout",
  44: "Dlayout",
  45: "Dlayout",
  46: "Llayout",
  47: "Jlayout",
  48: "Dlayout",
  49: "Flayout",
  50: "Hlayout",
  51: "Blayout",
  52: "Blayout",
  //   53: "Alayout",

  //   14: "Wlayout",
};
const popUpData = {
  0: "",
  1: "",
  2: "",
  3: "",
  4: [
    {
      title: "Estructura del Ciclo",
      typeofContent: "image",
      contentModal: "PAG4POP-1.png",
      buttonName: "+",
    },
    {
      title: "Enfoque restaurativo dentro del sistema educativo",
      typeofContent: "text",
      contentModal:
        "<b>¡Te damos la bienvenida a este espacio de aprendizaje y reflexión! </b> A lo largo de este curso, exploraremos herramientas y estrategias para la resolución de conflictos y la construcción de una convivencia basada en el diálogo, el respeto y la justicia restaurativa. <br> <br> <b>Tu rol es clave para la transformación educativa. </b> Este curso es una oportunidad para fortalecer",
      buttonName: "+",
    },
  ],
  5: "",
  6: "",
  7: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG7POP-1.png",
      buttonName: "CONVENCIÓN DE LOS DERECHOS DE​L NIÑO/A​​ ",
    },
  ],
  8: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG8POP-1.png",
      buttonName: "Constitución Política del Estado ",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-2.png",
      buttonName: "Ley N° 070 deEducación",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-3.png",
      buttonName: "Ley N° 348",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-4.png",
      buttonName: "Ley N° 348 - Ámbito educativo",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-5.png",
      buttonName: "Ley N° 548",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-6.png",
      buttonName: "Ley N° 548 - Medidas preventivas",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-7.png",
      buttonName: "Ley N° 548 - Tipos de violencia",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-8.png",
      buttonName: "Ley N° 548 - Discriminación",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-9.png",
      buttonName: "Reglamento Ley N° 548",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-10.png",
      buttonName: "Reglamento Ley N° 548",
    },
  ],
  9: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG8POP-1.png",
      buttonName: "Resolución Ministerial N° 001/2018 - Artículo 10 ",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-2.png",
      buttonName: "Resolución Ministerial N° 001/2018 - Artículo 89",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-3.png",
      buttonName: "Resolución Ministerial 1204/2018 - Artículo 3",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-4.png",
      buttonName: "Resolución Ministerial 1204/2018 - Parrafo III",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-5.png",
      buttonName: "Resolución Ministerial 1204/2018 - Parrafo IV y V",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-6.png",
      buttonName: "Resolución Ministerial 1204/2018 - Parrafo VI y VII",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-7.png",
      buttonName: "Resolución Ministerial N° 0001/2024 - Artículo 93 y 94",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-8.png",
      buttonName: "Resolución Ministerial N° 0001/2024 - Artículo 95",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-9.png",
      buttonName: "Resolución Ministerial N° 864/2019",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-10.png",
      buttonName: "Resolución Ministerial N° 864/2019",
    },
  ],
  10: "",
  11: "",
  12: "",
  13: "",
  14: "",
  15: "",
  16: [
    // {
    //   title: "Titulo del modal000DDD",
    //   typeofContent: "image",
    //    contentModal: "layOutD.jpg",
    //    buttonName: "IR1",
    //  },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG16POP-1.png",
      buttonName: "+",
    },
  ],
  17: [
    // {
    //   title: "Titulo del modal000DDD",
    //   typeofContent: "image",
    //    contentModal: "layOutD.jpg",
    //    buttonName: "IR1",
    //  },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG17POP-1.png",
      buttonName: "+",
    },
  ],
  18: "",
  19: [
    {
      title: "Titulo del modal000DDD",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "IR1",
    },
    {
      title: "Titulo del modal1111DDD",
      typeofContent: "text",
      contentModal:
        "1111DDDDLorem del MODAL ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum",
      buttonName: "IR2",
    },
  ],
  20: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG20POP-1",
      buttonName: "Relaciones Sociales",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG20POP-2",
      buttonName: "Independencia y Autonomia",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG20POP-3",
      buttonName: "Temas de conflicto",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG20POP-4",
      buttonName: "Comunicación",
    },
    {
      title: "TITULO5",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "POP UP BUTTON5",
    },
  ],
  21: "",
  22: [
    {
      title: "Titulo del modal000DDD",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "IR1",
    },
    {
      title: "Titulo del modal1111DDD",
      typeofContent: "text",
      contentModal:
        "1111DDDDLorem del MODAL ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum",
      buttonName: "IR2",
    },
  ],
  23: [
    {
      title: "Factores de Riesgo",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "Individual",
    },
    {
      title: "TFactores de Riesgo",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "Familiar",
    },
    {
      title: "Factores de Riesgo",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "Entre pares",
    },
    {
      title: "Factores de Riesgo",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "Escolar",
    },
    {
      title: "Factores de Riesgo",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "Comunidad",
    },
  ],
  24: "",
  25: "",
  26: [
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "Qué es la violencia",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "Qué es violencia psicologica - maltrato verbal",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "Qué es violencia psicologica - maltrato emocional",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "Qué es violencia físico",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "Qué es violencia físico - manifestaciones",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "Qué es violencia por negligencia",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "Qué es violencia por negligencia",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "Qué es la violencia sexual",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "Qué es la violencia sexual",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "Qué es la violencia sexual",
    },
  ],
  27: "",
  28: "",
  29: "",
  30: [
    {
      title: "TITULO1",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "POP UP BUTTON1",
    },
    {
      title: "TITULO2",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "POP UP BUTTON2",
    },
    {
      title: "TITULO3",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "POP UP BUTTON3",
    },
    {
      title: "TITULO4",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "POP UP BUTTON4",
    },
    {
      title: "TITULO5",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "POP UP BUTTON5",
    },
  ],
  31: [
    {
      title: "",
      typeofContent: "text",
      contentModal:
        "GGGGLorem del MODAL ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum",
      buttonName: "POP UP BUTTON",
    },
  ],
  32: "",
  33: "",
  34: "",
  35: "",
  36: [
    {
      title: "",
      typeofContent: "text",
      contentModal:
        "GGGGLorem del MODAL ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum",
      buttonName: "POP UP BUTTON",
    },
  ],
  37: [
    {
      title: "Titulo del modal000DDD",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "IR1",
    },
    {
      title: "Titulo del modal1111DDD",
      typeofContent: "text",
      contentModal:
        "1111DDDDLorem del MODAL ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum",
      buttonName: "IR2",
    },
  ],
  38: "",
  39: "",
  40: [
    {
      title: "Titulo del modal000",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "GO00",
    },
    {
      title: "Titulo del modal1111",
      typeofContent: "text",
      contentModal:
        "1111Lorem del MODAL ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum",
      buttonName: "GO11",
    },
  ],
  41: [
    {
      title: "Titulo del modal000",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "GO00",
    },
    {
      title: "Titulo del modal1111",
      typeofContent: "text",
      contentModal:
        "1111Lorem del MODAL ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum",
      buttonName: "GO11",
    },
  ],
  42: "",
  43: [
    {
      title: "TITULO1",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "POP UP BUTTON1",
    },
    {
      title: "TITULO2",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "POP UP BUTTON2",
    },
    {
      title: "TITULO3",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "POP UP BUTTON3",
    },
    {
      title: "TITULO4",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "POP UP BUTTON4",
    },
    {
      title: "TITULO5",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "POP UP BUTTON5",
    },
  ],
  44: [
    {
      title: "Titulo del modal000DDD",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "IR1",
    },
    {
      title: "Titulo del modal1111DDD",
      typeofContent: "text",
      contentModal:
        "1111DDDDLorem del MODAL ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum",
      buttonName: "IR2",
    },
  ],
  45: [
    {
      title: "Titulo del modal000DDD",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "IR1",
    },
    {
      title: "Titulo del modal1111DDD",
      typeofContent: "text",
      contentModal:
        "1111DDDDLorem del MODAL ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum",
      buttonName: "IR2",
    },
  ],
  46: [
    {
      title: "TITULO1",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "POP UP BUTTON1",
    },
    {
      title: "TITULO2",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "POP UP BUTTON2",
    },
    {
      title: "TITULO3",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "POP UP BUTTON3",
    },
    {
      title: "TITULO4",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "POP UP BUTTON4",
    },
    {
      title: "TITULO5",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "POP UP BUTTON5",
    },
  ],
  47: "",
  48: [
    {
      title: "Titulo del modal000DDD",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "IR1",
    },
    {
      title: "Titulo del modal1111DDD",
      typeofContent: "text",
      contentModal:
        "1111DDDDLorem del MODAL ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum",
      buttonName: "IR2",
    },
  ],
  49: "",
  50: [
    {
      title: "TITULO1",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName:
        "Resolución ministerial N° 864/2019. Protocolo de prevención, actuación y denuncia en casos de violencia",
    },
    {
      title: "TITULO2",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "POP UP BUTTON2",
    },
    {
      title: "TITULO3",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "POP UP BUTTON3",
    },
    {
      title: "TITULO4",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "POP UP BUTTON4",
    },
    {
      title: "TITULO5",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "POP UP BUTTON5",
    },
    {
      title: "TITULO6",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "POP UP BUTTON6",
    },
    {
      title: "TITULO7",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "POP UP BUTTON7",
    },
    {
      title: "TITULO8",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "POP UP BUTTON8",
    },
    {
      title: "TITULO9",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "POP UP BUTTON9",
    },
    {
      title: "TITULO10",
      typeofContent: "image",
      contentModal: "layOutD.jpg",
      buttonName: "POP UP BUTTON10",
    },
  ],
  51: "",
  52: "",
  53: " ",

  //   14: [
  //     {
  //       title: "Titulo del modal000DDD",
  //       typeofContent: "image",
  //       contentModal: "layOutD.jpg",
  //       buttonName: "IR1",
  //     },
  //     {
  //       title: "Titulo del modal1111DDD",
  //       typeofContent: "text",
  //       contentModal:
  //         "1111DDDDLorem del MODAL ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum",
  //       buttonName: "IR2",
  //     },
  //   ],
};
const imagesData = {
  0: "",
  1: "",
  2: "",
  3: "",
  4: "PAG4-1.png",
  5: "PAG5-1.png",
  6: ["layOutD.jpg", "PAG6-1.png"],
  7: "",
  8: "",
  9: "",
  10: ["PAG10-1.png", "PAG10-2.png"],
  11: ["actividad_inicio.png", "PAG6-1.png"],
  12: "PAG12-1.png",
  13: ["actividad_inicio.png", "PAG6-1.png"],
  14: [
    "PAG14-1.png",
    "PAG14-2.png",
    "PAG14-3.png",
    "PAG14-4.png",
    "PAG14-5.png",
  ],
  15: "PAG15-1.png",
  16: "PAG16-1.png",
  17: "PAG17-1.png",
  18: ["PAG18-1.png", "PAG18-2.png", "PAG18-3.png", "PAG18-4.png"],
  19: "PAG19-1.png",
  20: "",
  21: [
    "PAG21-1.png",
    "PAG21-2.png",
    "PAG21-3.png",
    "PAG21-4.png",
    "PAG21-5.png",
  ],
  22: "PAG22-1.png",
  23: "PAG23-1.png",
  24: "PAG24-1.png",
  25: ["PAG25-1.png", "PAG25-2.png"],
  26: "PAG26-1.png",
  27: "PAG27-1.png",
  28: [
    "PAG28-1.png",
    "PAG28-2.png",
    "PAG28-3.png",
    "PAG28-4.png",
    "PAG28-5.png",
  ],
  29: "PAG29-1.png",
  30: "PAG30-1.png",
  31: "PAG31-1.png",
  32: "PAG32-1.png",
  33: ["actividad_inicio.png", "PAG33-1.png"],
  34: "PAG34-1.png",
  35: ["actividad_inicio.png", "PAG35-1.png"],
  36: "PAG36-1.png",
  37: "PAG37-1.png",
  38: "PAG38-1.png",
  39: "PAG39-1.png",
  40: "PAG40-1.png",
  41: "PAG41-1.png",
  42: "PAG42-1.png",
  43: "PAG43-1.png",
  44: "PAG44-1.png",
  45: "PAG45-1.png",
  46: "PAG46-1.png",
  47: [
    "PAG47-1.png",
    "PAG47-2.png",
    "PAG47-3.png",
    "PAG47-4.png",
    "PAG47-5.png",
  ],
  48: "PAG48-1.png",
  49: ["actividad_inicio.png", "PAG49-1.png"],
  50: "PAG50-1.png",
  51: "PAG51-1.png",
  52: "PAG52-1.png",
  53: "PAG53-1.png",

  //   14: "",
};

const buttonsNameData = {
  0: "",
  1: "",
  2: "",
  3: "",
  4: "",
  5: [
    "Normativa internacional",
    "Normativa nacional",
    "Protocolo de prevención",
    "Estrategias para la Prevención de Conflictos",
  ],
  6: "",
  7: "",
  8: "",
  9: "",
  10: "",
  11: "",
  12: [
    "El conflicto y sus características ",
    "Conflictos entre estudiantes ",
    "Factores de riesgo en la unidad educativa",
    "Violencia en el ámbito educativo",
  ],
  13: "",
  14: "",
  15: "",
  16: "",
  17: "",
  18: "",
  19: "",
  20: "",
  21: "",
  22: "",
  23: "",
  24: "",
  25: "",
  26: "",
  27: "",
  28: "",
  29: "",
  30: "",
  31: "",
  32: "",
  33: "",
  34: [
    "La importancia del enfoque restaurativo",
    "Diferencias entre el enfoque restaurativo y punitivo en el ámbito educativo ",
    "Características y principios del enfoque restaurativo ",
    "Ventana de la disciplina social",
  ],
  35: "",
  36: "",
  37: "",
  38: "",
  39: "",
  40: "",
  41: "",
  42: "",
  43: "",
  44: "",
  45: "",
  46: "",
  47: "",
  48: "",
  49: "",
  50: "",
  51: "",
  52: "",
  53: "",

  //   12: ["Boton1 ", "Boton2 ", "Boton3 "],
  //   13: "",
};

const buttonsPageNumberData = {
  0: "",
  1: "",
  2: "",
  3: "",
  4: "",
  5: [7, 8, 10, 11],
  6: "",
  7: "",
  8: "",
  9: "",
  10: "",
  11: "",
  12: [15, 19, 22, 24],
  13: "",
  14: "",
  15: "",
  16: "",
  17: "",
  18: "",
  19: "",
  20: "",
  21: "",
  22: "",
  23: "",
  24: "",
  25: "",
  26: "",
  27: "",
  28: "",
  29: "",
  30: "",
  31: "",
  32: "",
  33: "",
  34: [35, 38, 42, 45],
  35: "",
  36: "",
  37: "",
  38: "",
  39: "",
  40: "",
  41: "",
  42: "",
  43: "",
  44: "",
  45: "",
  46: "",
  47: "",
  48: "",
  49: "",
  50: "",
  51: "",
  52: "",
  53: "",

  //   12: ["Boton1 ", "Boton2 ", "Boton3 "],
  //   13: "",
};

const linksData = {
  0: "",
  1: "",
  2: "",
  3: "",
  4: "",
  5: "",
  6: "https://docs.google.com/document/d/1279QXm7hHXpcICKyRduFxn11gL_ShQEi/edit?usp=drive_link&ouid=118068284416475194361&rtpof=true&sd=true",
  7: "",
  8: "",
  9: "",
  10: "https://www.ddechuquisaca.gob.bo/app/documentos/PROTOCOLO%20DE%20PREVENCI%C3%93N%20DENUNCIAS%20AGRESIONES%20SEXUALES.pdf",
  11: "https://docs.google.com/document/d/1tdhPdn8Kx4Yp2Z5xlk5irNtZ-MK0zYRa/edit?usp=sharing&ouid=118068284416475194361&rtpof=true&sd=true",
  12: "",
  13: "https://docs.google.com/document/d/1DMv56j2fzPCWbXl85iyvxZSSIluFhDZK/edit?usp=sharing&ouid=118068284416475194361&rtpof=true&sd=true",
  14: "",
  15: "",
  16: "",
  17: "",
  18: "",
  19: "",
  20: "",
  21: "",
  22: "",
  23: "",
  24: "",
  25: "https://www.oep.org.bo/wp-content/uploads/2023/02/LEY-548-CODIGO-NINIA-NINIO-ADOLESCENTE.pdf",
  26: "",
  27: "",
  28: "",
  29: "",
  30: "",
  31: "",
  32: "",
  33: "https://docs.google.com/document/d/17LBSHrJP1vLnnVrzTLDSMkasGwxl0L5H/edit?usp=sharing&ouid=118068284416475194361&rtpof=true&sd=true",
  34: "",
  35: "https://docs.google.com/document/d/1wJCbTq50fWUPVSNioklgPWcpjAx1QqaT/edit?usp=sharing&ouid=118068284416475194361&rtpof=true&sd=true",
  36: "",
  37: "",
  38: "",
  39: "",
  40: "",
  41: "",
  42: "",
  43: "",
  44: "",
  45: "",
  46: "",
  47: "",
  48: "",
  49: "https://docs.google.com/document/d/14zIwR2sDe254Dy6FieMyPY5h5EYYWgi5/edit?usp=sharing&ouid=118068284416475194361&rtpof=true&sd=true",
  50: "",
  51: "",
  52: "",
  53: "",
};
