const textData = {
  0: "texto a remplazarA",
  1: "Cuaderno: De la justicia restaurativa a las prácticas educativas<br>, <br> Coordinación:<br> Viceministerio de Educación Superior de Formación Profesional Dirección General de Formación de Maestros<br>Unidad Especializada de Formación Continua - UNEFCO<br> <br> Equipo de redacción y dirección:<br>Fundación Ayuda en Acción ProgettoMondo<br>Unidad Especializada de Formación Continua - UNEFCO<br>",
  2: "texto a remplazarC",
  3: "<b> Presentación </b> <br>  El Plan de Formación para Maestras y Maestros es una modalidad de aprendizaje, compuesta por cursos cortos, desarrollada por el Ministerio de Educación a través de la Unidad Especializada de Formación Continua (UNEFCO) para profundizar y fortalecer habilidades y capacidades en la labor educativa, con un enfoque en la mejora de las prácticas y procesos formativos. Su propósito, de acuerdo con la Ley de Educación N° 070 “Avelino Siñani – Elizardo Pérez”, es trabajar por la universalización del Modelo Educativo Sociocomunitario Productivo, en atención a los diferentes niveles y áreas temáticas, con relevancia cultural y lingüística. <br> <br> Las prácticas restaurativas se han venido consolidando como una ciencia social emergente desde aproximadamente el 2013, época en la cual se estudian las acciones individuales y efectivas dirigidas hacia tres objetivos: el fortalecimiento comunitario, la resolución pacífica de conflictos y la	del daño o falta u ofensa cuando se produce. Se definen las mismas como respuestas no punitivas orientadas a la reparación del daño, potenciar las relaciones interpersonales, fortalecer la resolución de los conflictos y desarrollar soluciones que incluyan a todas las personas involucradas en un daño o falta u ofensa; tomando en cuenta que el manejo restaurativo de los afectos en el aula mejora la capacidad para el aprendizaje y la resiliencia. <br> <br> Los cuadernos del ciclo formativo: <b> “PRÁCTICAS RESTAURATIVAS PARA LA RESOLUCIÓN DE CONFLICTOS Y UNA VIDA LIBRE DE VIOLENCIA” </b>, nos invitan a replantearnos la manera en que enfrentamos los conflictos, desafiando los paradigmas arraigados de confrontación y castigo. A medida que nos sumergimos en las profundidades de las prácticas restaurativas, descubrimos su capacidad no solo para restaurar el daño o falta u ofensa causado por los conflictos, sino también para fortalecer nuestros lazos comunitarios y fomentar un clima de confianza y respeto mutuo. Este ciclo cuenta con tres cursos, en el Primer Curso, se aborda la parte normativa, lo que es y no es conflicto para luego introducir al enfoque restaurativo; en el Segundo Curso, se presenta; y en el Tercer Curso presentamos una caja de herramientas práctica para la aplicación en el quehacer educativo. <br> <br><b>Jorge Galindo Villa Castro COORDINADOR GENERAL – UNEFCO</b>",
  4: "<b>OBJETIVO HOLÍSTICO DEL CICLO</b> <br>Fortalecemos en maestras y maestros la responsabilidad de ser los principales actores en la resolución de conflictos, desarrollando su análisis y reflexión sobre los principios del enfoque restaurativo, promoviendo la incorporación de las prácticas restaurativas en sus procesos de interacción cotidianos, tomando decisiones para la promoción de una convivencia, pacífica, armónica y libre de violencia en su comunidad educativa. <br><br> <b> OBJETIVO HOLÍSTICO DEL CURSO</b><br> Identificamos condiciones para prácticas educativas restaurativas, su implementación en la resolución de conflictos y a la prevención de la violencia, con participación activa de integrantes de la comunidad educativa, para contar con espacios educativos restaurativos. <br>",
  5: " ",
  6: "Instructivo actividad 1",
  7: ["Maestras y maestros desarrollan dinámicas de resolución de conflictos a partir de una cultura restaurativa, para una convivencia pacífica.", "Tenemos que tomar en cuenta que los programas de justicia restaurativa están basados en el principio fundamental que la conducta antisocial no es solo infringir la norma o las leyes, es también el daño, falta u ofensa que se realiza a una víctima que es parte de una comunidad.", ". La aplicación de la práctica restaurativa se dará a través de la resolución de los conflictos, de manera que cuando una de las personas cometía una infracción, un daño o falta u ofensa o una ofensa se utilizan prácticas de diálogo y reparación, es ofrecer un espacio de encuentro a todas las personas relacionadas con el hecho que de una u otra manera fueron parte; ya sea como víctimas, como espectadores pasivos o activos, como persona que realiza la ofensa y otros."],
  8: " ",
  9: "En el artículo El enfoque de la justicia restaurativa, López señala que de acuerdo a la European Forum of Restorative Justice se establece los siguientes principios básicos:<br> <br> <b>Restauración y reparación: </b> el proceso restaurativo debe proporcionar una experiencia de justicia, donde cada participante se responsabilice en restaurar lo dañado a través del delito, abordando tanto las causas como las consecuencias del mismo.<br> <br> <b>Voluntariedad:</b> todas las partes deben manifestar su voluntariedad en la participación, es importante que dicha voluntariedad sea acompañada de información clara sobre el proceso, especialmente si este tiene consecuencias legales. Esta voluntariedad pueden retirarla en cualquier momento.<br> <br> <b>Inclusión:</b> el proceso de inclusión debe atender a la diversidad de necesidades, culturas y capacidades de las personas que participen, y tener las mismas posibilidades y oportunidades de participar en el proceso, adaptando las diferentes fases a la misma.<br>  <br>  <b>Participación:</b> se debe fomentar la participación de las personas de forma respetuosa, justa y segura para ofrecer un diálogo.<br> <br>  <b>Compromiso:</b> en caso de llegar a un acuerdo de reparación, este acuerdo debe ser apoyado y sostenido por las personas responsables.<br> <br> <b>Confidencialidad:</b> el proceso debe ser confidencial, para ello las personas implicadas deben dar su consentimiento sobre el mismo y ser consciente de cualquier excepción de la confidencialidad.” (López, 2023)<br> ",
  10: "Las consecuencias de la violencia son diferentes, según la acción u omisión que se ejerce contra <b>una niña, un niño o adolescente</b> y depende de diversos factores como: <b>el tipo de conducta, la relación de la agresora o del agresor con la víctima, la frecuencia, la relación del contexto</b>, etc. que suponen <b>efectos inmediatos y, en ocasiones, crónicos</b> si no se interviene de forma temprana y adecuada. <br>  Por lo general, cuando hay consecuencias físicas, éstas son identificables porque <b>dejan huellas en el cuerpo</b> y, la mayoría de las veces, son visibles; sin embargo, este tipo de violencia viene acompañada con <b>una gran carga de violencia psicológica que no siempre es visible y aparentemente no deja marcas</b>, por lo tanto, muchas veces <b>no son atendidas de manera inmediata</b>.",
  11: " ",
  12: "La violencia escolar incluye <b>agresiones físicas (golpes, puñetazos, patadas)</b>, <b>agresiones verbales (amenazas, burlas, apodos, rumores, entre otros)</b>, <b>exclusión social</b>, y además pueden presentarse <b>agresiones sexuales (tocamientos no consentidos, abuso sexual -que no se enmarquen en la comisión de un delito-)</b>. </br> Cuando estas violencias se manifiestan entre pares de manera repetida y contemplan <b>un desequilibrio en el poder entre quien ejerce el maltrato y quien lo recibe, con la intención de lastimar</b>, entonces se trata de maltrato entre pares; es decir, entre iguales, este tipo de violencia puede darse <b>al interior de los grupos que conforman la comunidad educativa (estudiantes, maestros/maestras, personal administrativo)</b>. También existe el maltrato entre no pares; es decir, en <b>personas de grupos diferentes que son parte de la comunidad educativa (maestra/maestro contra estudiante, estudiante contra maestra/maestro, directivo contra maestra/maestro)</b>.",
  13: " ",
  14: [" El bullying, acoso escolar o maltrato entre pares se presenta <b>tanto en niñas, niños de primaria como en adolescentes y jóvenes, mujeres y hombres</b>. De hecho, suele atribuirse a adolescentes, mujeres u hombres, que manifiestan ciertas características consideradas propias de <b>maltratadores típicos, tales como una tiranía premeditada, continua, malévola y despreciable; graves problemas de conducta desde edades tempranas, agresividad, robo de cosas, mentiras constantes y consumo de sustancias psicoactivas</b>. (Maritza Garcia y Cristian Amaury, 2019)", "Las formas que adquiere el acoso escolar o bullying son <b>verbales (insultos, majaderías, burlas, bromas pesadas)</b>; <b>físicas (empujones, patadas, pellizcos, golpes, romper la ropa)</b>; <b>sexuales (tocamientos irrespetuosos)</b>; <b>sociales, de indiferencia y ostracismo (el hacer a un lado a la persona, sobre todo del grupo)</b>; <b>virtuales, mediante el cyberbullying o intimidación por la red, ya sea a través de teléfonos móviles o de redes sociales, como Facebook, Twitter, o por correos electrónicos o páginas virtuales</b>. (Maritza Garcia y Cristian Amaury, 2019)"],
  15: ["En la actualidad, el bullying o acoso escolar se relaciona con las nuevas tecnologías que ponen al alcance niveles mayores de daño o falta u ofensa, humillación y anonimato al impedir el contacto de las capas emocionales que inhiben la agresión; esto da lugar a prácticas de maltrato que rebasan las fronteras espaciotemporales.", "La violencia entre pares <b>casi siempre tiene lugar lejos de la presencia de personas adultas, maestras/maestros, madre/padre, otros del mundo adulto</b>. Dado que <b>las consecuencias pueden llegar a ser irreversibles para la integridad personal, el equilibrio psicológico y el rendimiento académico de la víctima</b>, es necesaria <b>su identificación oportuna para intervenir lo antes posible con las medidas educativas y de protección previstas para estos casos</b>."],
  16: "Las consecuencias de la violencia son diferentes, según la acción u omisión que se ejerce contra <b>una niña, un niño o adolescente mujer y hombre</b> y depende de <b>diversos factores como: el tipo de conducta, la relación de la agresora o del agresor con la víctima, la frecuencia, la relación del contexto</b>, etc. que suponen <b>efectos inmediatos y, en ocasiones, crónicos si no se interviene de forma temprana y adecuada</b>. Por lo general, cuando hay consecuencias físicas, éstas son identificables porque <b>dejan huellas en el cuerpo y, la mayoría de las veces, son visibles</b>; sin embargo, este tipo de violencia viene acompañada con <b>una gran carga de violencia psicológica que no siempre es visible y aparentemente no deja marcas</b>, por lo tanto, muchas veces <b>no son atendidas de manera inmediata</b>. <br> Las niñas, los niños y adolescentes (mujeres u hombres) víctimas de violencia, en el mediano y largo plazo, pueden experimentar <b>consecuencias de carácter físico y/o psicosomático que afectan tanto la esfera afectiva, emocional, conductual y social de las víctimas</b>, desarrollando <b>hábitos disfuncionales y conductas de riesgo</b>, pero sobre todo que <b>influyen en la pérdida de confianza en sí mismos y en los demás</b>, por lo que manifiestan <b>dificultades para la interacción social y las relaciones afectivas</b>.",
  17: " ",
  18: ["La <b>Justicia Restaurativa</b> es una filosofía y una propuesta educativa integral que se basa en el <b>respeto mutuo</b> y la <b>resolución pacífica de conflictos</b> en la comunidad educativa. Las <b>prácticas restaurativas</b>, como herramientas sencillas pero efectivas, contribuyen a establecer <b>relaciones sanas y fuertes</b> entre cada integrante y estamento de la comunidad educativa, crear <b>espacios de diálogo</b>, fomentar el <b>liderazgo positivo</b> y el <b>empoderamiento</b>, promover <b>comportamientos responsables</b> y reducir los <b>comportamientos violentos</b>, y <b>reparar el daño</b> y <b>restaurar las relacones</b>. (Edu Calidad; la convivencia hacia la diferencia, 2024). <br>  La <b>Justicia Restaurativa</b> se enfoca en las <b>víctimas</b> y busca <b>reparar el daño</b> cometido a través del conflicto o la comisión de delito, mientras que la <b>práctica restaurativa</b> se puede aplicar de forma <b>proactiva</b>, <b>preventiva</b> y <b>reactiva</b>, y no necesita que exista delito para aplicarse. La <b>práctica restaurativa</b> tiene como fin crear <b>sentido de comunidad</b> de tal forma que puedan reducirse la cantidad de conflictos (diariodemediacion.es, 2018).","Las <b>prácticas restaurativas</b> en el ámbito educativo abordan los conflictos desde un enfoque <b>social</b>, <b>afectivo</b>, <b>pedagógico</b> y de <b>derechos</b>, orientado por los principios de <b>protección integral</b> e <b>interés superior</b> de niñas, niños y adolescentes (mujeres y hombres). Diferentes investigaciones prueban que el modelo de <b>gestión de conflictos</b> basado en el enfoque restaurativo <b>frena la reincidencia</b>, facilita la <b>restauración de relaciones</b> entre las personas implicadas, ayuda a instaurar un <b>sentimiento de pertenencia</b> a la comunidad, favorece la <b>reparación de los daños</b> en el grupo de estudiantes víctimas o en el caso que haya sido una víctima de manera individual y aumenta la <b>implicación personal</b> en la resolución del conflicto y la <b>reparación del daño</b>."],
  19: "Tenemos que tener presente que las <b>prácticas restaurativas</b> surgen como una <b>ciencia social</b> que nos permite procesos de <b>restauración</b> y construcción de <b>“comunidad”</b>, entendida ésta como el conjunto de <b>relaciones</b> que entretejen las personas; emerge el <b>sentimiento de pertenecer</b> a un grupo e <b>intereses comunes</b>. Es una relación construida sobre el <b>afecto</b>, los <b>fines</b> y los <b>valores comunes</b>, así́ como en la <b>lealtad</b> y la <b>reciprocidad</b> entre todos sus integrantes.<br> Recordamos que es una <b>disciplina</b> que nos permite construir un <b>capital social</b> a través de procesos de <b>aprendizaje</b> y <b>toma de decisiones</b> de manera <b>voluntaria</b> y <b>participativa</b>, generando así estas prácticas restaurativas <b>espacios seguros de diálogo</b>, afrontando situaciones tensas de <b>conflicto</b> desde una <b>perspectiva restaurativa</b>, para <b>reparar las relaciones</b> rotas o afectadas.",
  20: "",
  21: "Insstructivo actividad 2",
  22: " ",
  23: "Insstructivo actividad 3",
  24: ["<b>La práctica restaurativa</b> es una alternativa a las políticas excluyente y punitivas que se dan a través de una convivencia tradicional donde aún se practica una disciplina basada en la culpabilidad y el castigo, a pesar de que existen investigaciones que muestran que estas son ineficaces en la prevención de las conductas no adecuadas; más al contrario, muchas veces, agravan los problemas de disciplina y lleva a algunos estudiantes a tener problemas de comisión de delito", "Este proceso puede ser denominado como una <b>comunidad restaurativa</b> porque es el esfuerzo de todas las personas que conforman la comunidad educativa: estamento estudiantil <b>-niñas, niños y adolescentes-</b>, maestras, maestros, madres/padres o tutores de familia, personal de dirección."],
  25: " ",
  26: "<b>Maestras y maestros</b> pueden ser <b>facilitadores</b> de <b>prácticas restaurativas</b> en el ámbito educativo. “Estas prácticas buscan <b>mejorar la convivencia escolar</b> al crear <b>vínculos</b> entre los miembros de la comunidad, resolviendo <b>conflictos</b> a partir del <b>diálogo</b> y creando <b>entornos positivos</b> con la <b>participación</b> de toda la comunidad educativa”. (educacionyfp.gob.es, 2020). <br> La figura de la persona que actúa <b>facilitando</b> en las prácticas restaurativas es recomendable que sea <b>asumida</b> y <b>comprendida</b> por <b>maestras y maestros</b>, <b>personal directivo</b> y <b>personal administrativo</b> en su plenitud, para que así puedan <b>realizar</b> y <b>organizar</b>, tanto las prácticas como la <b>metodología de intervención</b> en la comunidad educativa.",
  27: " ",
  28: "<b>Promover las prácticas restaurativas</b> en la comunidad educativa por parte de <b>maestras y maestros</b> es importante, siendo que estos se convierten en el <b>agente de cambio</b>, previniendo la <b>vulneración de derechos</b> de estudiantes, como también <b>futuros problemas de conducta</b>, evitando el surgimiento de la <b>violencia</b>, y evitando que estudiantes se acerquen a la <b>comisión de delito</b>.<br>No debemos olvidar que dependerá de <b>maestras y maestros</b> <b>establecer las conexiones</b> en el aula, creando <b>oportunidades</b> para que estudiantes, niñas, niños y adolescentes, mujeres y hombres, puedan <b>establecer conexiones</b>, estén en relación con el <b>aprendizaje académico</b> y, también, con estudiantes de su curso y <b>nivel estudiantil</b>.",
  29: ["Ante  una situación de conflicto maestra o maestro o es quien genera el proceso de mediación en la comunidad educativa, soluciona los conflictos de manera neutral e independiente, este proceso permite desarrollar un ambiente escolar más relajado y productivo.", "Se debe evitar ser observador pasivo de conflictos que en los que pudieren estar estudiantes de la comunidad educativa, más al contrario, debe intervenir inmediatamente ante conflictos y situaciones de violencia leves, con el fin de detener el ciclo de la violencia y proponer modos de resolución de conflictos por la vía pacífica"],
  30: "<b>Maestras y maestros</b> y el <b>personal administrativo</b> de la unidad educativa pueden ayudar en la <b>resolución de conflictos</b> y la <b>prevención de violencias</b>; sin embargo, no debemos olvidar que <b>madres/padres</b> y <b>tutores</b> de familia son <b>actores importantes</b> para que también se pueda implementar las prácticas  <b>restaurativas</b>. <br> De acuerdo con el <b>Reglamento de Participación Social Comunitario en Educación</b>, <b>padres y madres de familia</b>, <b>Juntas Escolares</b>, y los <b>Concejos Educativos</b> deben apoyar acciones de <b>prevención</b> y <b>control</b> contra todo tipo de <b>violencia</b> dentro de la <b>Unidad Educativa</b>, en coordinación con las <b>autoridades educativas</b>.",
  31: " ",
  32: ["Los procesos de prácticas restaurativas en comunidades educativas coadyuvan a la prevención de violencias entre los diferentes actores de la comunidad. Siendo uno de ellos: niñas, niños, adolescentes, es decir, estudiantes, mujeres y hombres, quienes al promover y ser parte de los procesos restaurativos pueden emitir sus opiniones, sus sentimientos ante una situación de conflicto en la que está involucrado directa e indirectamente.", "En ese sentido se hace necesario que estudiantes reciban una formación en la implementación de las prácticas restaurativas, siendo que al conocer los instrumentos o mecanismos de la misma, se fortalecerá también diferentes habilidades sociales personales, la cohesión grupal, la importancia de ser parte de una comunidad educativa y reconocer que toda conducta influye a todo el sistema educativo."],
  33: [" El grupo de estudiantes, mujeres u hombres, al ser participantes activos del proceso, naturalmente tienen una percepción positiva de la metodología y recomiendan la implementación de prácticas restaurativas. Aun así, cobra relevancia que la perspectiva de ellos se orienta a que estos sean más escuchados por las personas adultas y que ellos, como estamento estudiantil estén mejor capacitados para resolver conflictos, además que el trabajo entre pares es más factible de realizarlo.", "Involucrar a estudiantes en la resolución de conflictos de y con sus pares, en algunas situaciones se hace más productivo siendo que el proceso puede ser implementado desde un punto de vista, más de sus vivencias, considerando que tienen las mismas edades."],
  34: "La <b>participación</b> de <b>madre, padre o tutor</b> de familia en <b>procesos restaurativos</b> es importante, porque las familias provienen de <b>distintos entornos</b>, con <b>formas de analizar la realidad</b> y determinadas <b>maneras de ver la realidad</b> y una <b>cultura</b> que son transmitidos a <b>hijas e hijos</b>. <br> Cabe mencionar que la <b>infancia</b>, como la <b>adolescencia</b>, son etapas donde hay <b>diferentes cambios</b> en niñas, niños y mujeres y hombres adolescentes, los cuales a veces generan <b>conflictos</b> con las familias y la <b>unidad educativa</b>. Es por ello por lo que se hace necesario que <b>madre/padre o tutor</b> de familia puedan ser <b>partícipes continuamente</b> de estos procesos, que <b>beneficiará</b> a sus hijos e hijas, no olvidando que forman parte de una <b>comunidad educativa</b>.",
  35: "Instructivo actividad 4",
  36: "",
  37: "instructivo actividad 5",
  38: ["Podemos identificar dos finalidades en el desarrollo de las prácticas restaurativas, la primera de ellas está en la <b> prevención de maltrato, daño u ofensa que puede darse entre pares y no pares</b>, mediante un abordaje asertivo de las situaciones de violencias en la unidad educativa; y, la segunda está en relación con la <b> búsqueda de la responsabilidad, a veces, de la corresponsabilidad y la reparación del daño por parte de la víctima </b>, de la persona que actúa como ofensor y de la comunidad, en general, cuando se ha producido acciones que están en relación con la violencia.", "Es decir que por estos mismos motivos se estable una doble condición: por un lado, como estrategias para la prevención, referidas a la posibilidad de emitir acciones que impidan o eviten esas acciones de maltrato o violencia en la unidad educativa; por otra parte, también son herramientas que permiten que se pueda atender y buscar el restablecimiento de las relaciones sociales que se deterioran a causa de una acción ya cometida"],
  39: " ",
  40: "En una zona restaurativa, cada integrante de la comunidad educativa cumple un rol fundamental en la construcción de un entorno basado en el respeto, la reparación del daño y la convivencia pacífica. Los niños, niñas, adolescentes y adultos ofensores son beneficiarios directos del proceso restaurativo, en el que se busca generar conciencia sobre la responsabilidad de sus acciones y su impacto en los demás, promoviendo su reintegración y cambio de conducta. <br> Las bases de una comunidad educativa (Hopkins, 2020) está conformada por los actores que intervienen en las prácticas restaurativas en las unidades educativas son:",
  41: "<b> Planificación docente </b> <br><br> Es importante que la maestra o el maestro elabore un plan de práctica restaurativa para una convivencia pacífica y armónica, cuya finalidad es abordar las problemáticas sociales y/o conflictos en las unidades educativas de manera restaurativa y no así punitiva.<br> <br>  <b>  Directrices para un reglamento interno con enfoque restaurativo </b> <br><br>  Las directrices de contenido de un reglamento interno con enfoque restaurativo deben contemplar los siguientes puntos, sin olvidar la Ley 548 Código de la Niña, Niño y Adolescente.",
  42: "Invitamos a revisar el Ciclo Formativo “Planes de Convivencia Pacífica y Armónica, donde encontrarás mayor detalle de este apartado",
  43: " ",
  44: "Las personas que han ido aplicando las <b>prácticas restaurativas</b> en su ámbito laboral, como <b>personal</b>, son de los que se puede recuperar <b>experiencias</b> y <b>vivencias enriquecedoras</b>, siendo uno de ellos la experiencia de <b>Jena Schmitz</b>, quien refiere lo siguiente: <br> “Las <b>comunidades educativas</b> con <b>cultura restaurativa</b> han desarrollado <b>relaciones sanas y seguras</b> entre todos sus actores, han promovido <b>comportamientos saludables y responsables</b>, han logrado reducir <b>comportamientos ofensivos y violentos</b>, han prevenido y gestionado <b>tensiones y conflictos</b>, han generado estudiantes <b>empáticos</b>, <b>responsables</b>, <b>empoderados</b> y con <b>liderazgo</b>, y aunque parezca sorprendente, han mejorado también el <b>rendimiento académico</b> del estudiantado.”  <br> “Un <b>centro educativo restaurativo</b> es un espacio que considera las <b>relaciones interpersonales</b> como elementos claves e indispensables para la <b>convivencia sana y pacífica</b>. Por ello, su principal objetivo es crear un <b>sentido de comunidad</b> entre todos sus actores, desarrollando, fortaleciendo y manteniendo <b>relaciones sanas, seguras y fuertes</b>, buscando prevenir <b>situaciones tensas, problemáticas y conflictivas</b>, abordándolas oportunamente cuando ocurran, implicando a todos los involucrados para <b>comprender la situación</b> y encontrar juntos la <b>mejor solución</b> a lo sucedido, <b>reparando los daños</b> o faltas u ofensas causados y evitando que vuelva a suceder en el futuro. Todo <b>conflicto</b> es una profunda fuente de <b>aprendizaje</b>.” (Manuel Ortega, VVOB Ecuador, 2022)",
  45: "Las <b>vivencias</b> logradas en <b>prácticas restaurativas</b> en las <b>comunidades educativas</b> son valiosas para mejorar la <b>convivencia</b> y gestionar <b>conflictos</b> de manera efectiva. Algunas de estas experiencias incluyen: <br>  • La importancia del <b>diálogo</b>: El diálogo es fundamental para entender las <b>expectativas</b> de todas las partes involucradas y para encontrar <b>soluciones</b> que sean aceptadas por todos. (www.pazatidea.org, 2022) <br>  • La <b>participación activa</b> de la comunidad: La implicación de <b>estudiantes</b>, <b>maestras y maestros</b>, <b>directoras/es</b>, <b>personal administrativo</b> y <b>madres y padres de familia</b> es crucial para el éxito de las prácticas restaurativas. <br>  • La necesidad de <b>preparación y formación</b>: Para llevar a cabo prácticas restaurativas efectivas, es esencial que los <b>facilitadores</b> estén bien preparados y formados en técnicas de <b>mediación</b> y <b>resolución de conflictos</b>. <br>  • El enfoque en la <b>reparación del daño</b> o falta u ofensa: Más allá del castigo, se busca <b>reparar el daño</b> o falta u ofensa causado y <b>restaurar las relaciones</b> dañadas. <br> • La <b>prevención es clave</b>: Las prácticas restaurativas no solo sirven para resolver conflictos, sino también para <b>prevenirlos</b>, creando un ambiente escolar basado en el <b>respeto mutuo</b> y la <b>comprensión</b>. (www.wp.catedu.es, 2021). <br>  • El <b>fortalecimiento de los vínculos</b>: Estas prácticas ayudan a fortalecer las <b>relaciones</b> dentro de la comunidad educativa, lo que contribuye a lograr un entorno más <b>armónico</b> y <b>colaborativo</b>. (www.pazatidea.org, 2022) <br>",
  46: "",
  47: "Las <b>zonas restaurativas</b> en las comunidades educativas son <b>espacios diseñados</b> para fomentar la <b>convivencia sana y segura</b>, utilizando la <b>filosofía restaurativa</b> como base. Esta se fundamenta en la convicción de que se puede mejorar la <b>convivencia humana</b> cuando las personas se sienten que forman parte de una <b>comunidad</b> y se sienten <b>escuchadas</b> y <b>respetadas</b>.<br> La implementación de <b>zonas restaurativas</b> en las comunidades educativas puede contribuir a la creación de un <b>ambiente escolar positivo</b>, en el que se protegen las <b>relaciones personales sanas</b> y se educa a los estudiantes en valores como el <b>respeto</b>, la <b>tolerancia</b> y el <b>compromiso</b>. Además, las <b>zonas restaurativas</b> pueden ser una <b>herramienta efectiva</b> para la <b>resolución de conflictos</b> y la <b>gestión de las relaciones</b> entre los miembros de la comunidad educativa. (<b>Albertí & Pedrol, 2017</b>)",
  48: "Instructivo actividad 6",
  49: ["Tomando en cuenta los contenidos desarrollados en el presente cuaderno de formación, llevamos adelante un diagnóstico que permita identificar los tipos de violencias, faltas que afectan a las y los estudiantes dentro de la comunidad educativa.","Analizamos qué información requerimos para identificar los tipos de faltas e infracciones (violencias) más frecuentes que enfrentan nuestras y nuestros estudiantes. <br>  Analizamos qué información requerimos para identificar las formas y/o resolución de conflictos en la comunidad educativa. <br> Recopilamos la información disponible con que cuenta la dirección sobre los casos conocidos durante la gestión sobre violencia entre pares. Al mismo tiempo de las formas que se ha ido utilizando para abordar este tipo de casos. <br> Realizamos entrevistas a los estudiantes para saber cuáles son los problemas y/o conflictos más recurrentes en este sentido. También es útil la información de las personas adultas de la comunidad educativa, es decir del plantel docente administrativo y el concejo educativo de padres, madres de familia.","<b>Según la información que hemos recolectado:</b><br> ¿Cuáles son los tipos de violencia, problemas y/o conflictos presentes entre las y los estudiantes? <br> ¿Qué género y edad realiza más faltas y/ o son parte de un conflicto? <br> ¿En qué medida resulta útil esta información?<br> ¿En qué medida las estadísticas ignoran a maestros y maestras?, ¿por qué? <br> "," <b> Conclusiones</b> <br> Sistematizamos la información y la plasmamos en gráficos y tablas sencillas.<br> Luego, sacamos las conclusiones que se desprenden de esta y, finalmente, trabajamos con un pequeño grupo de estudiantes para generar una zona restaurativa, aplicando prácticas restaurativas, con un enfoque preventivo, para analizar con ellos las alternativas para cambiar los hallazgos del diagnóstico. "," <b>Estrategias para la etapa de socialización de experiencias<b><br> <br> Compartimos en plenaria el proceso del diagnóstico y la metodología del recojo de la información, además de los logros y dificultades, y las conclusiones. <br> Compartimos también el proceso que tuvimos con los/as estudiantes en los círculos restaurativos y cómo pensamos que eso podría aportar a la convivencia. Finalmente, con apoyo de la facilitación, analizamos los aspectos relevantes que servirán para nuestra práctica diaria."],
  50: "<b>Comisión de delito</b>: El delito se caracteriza por ser una conducta descrita en el Código Penal, que es realizada por una persona natural, y puede, o no, tener la intención de hacer daño. Así́ mismo, debe ser comprobable mediante un juicio y existir un daño efectivo al bien jurídico de otro. <br> <br>   <b>Comunidad</b>: Es un concepto multidimensional que puede acoger tanto un espacio geográfico o territorio definido, como el conjunto de relaciones que entretejen las personas; así́, emerge el sentimiento de pertenecer a un grupo e intereses comunes. Es una relación construida sobre el afecto, los fines y los valores comunes, así́ como en la lealtad y la reciprocidad entre sus miembros. <br> <br>   <b>Comunidad Educativa</b>: Engloba a todos los miembros de la institución educativa, incluyendo estudiantes, directoras/es, maestras y maestros, personal administrativo, madres y padres de familias, que ayudan en la promoción de un ambiente de convivencia positiva. <br> <br>   <b>Corresponsabilidad</b>: Hace referencia al deber que tiene la familia, el Estado y la sociedad en relación con la atención cuidado y protección de estudiantes: niñas, niños y adolescentes, mujeres y hombres. <br> <br>   <b>Delito y/o falta</b>: Se refiere a aquellas acciones que, además más allá de afectar a una persona en particular, tienen repercusiones en el entorno educativo en su conjunto. <br> <br>   <b>Delito</b>: Es un comportamiento de manera voluntaria o por imprudencia atenta contra los derechos de otras personas, es una acción u omisión que puede convertirse en una infracción de la ley penal, de las normas establecidas. Atenta contra las personas, cuando se trata de vulnerar derechos como el respeto y la dignidad, por ejemplo, cuando se presenta violencia física o sexual y el respeto a la propiedad privada. <br> <br>",
  51: "<b>Disciplina</b>: En el ámbito educativo, la disciplina se refiere al conjunto de normas que regulan la convivencia en las unidades educativas. Estas normas no solo se refieren al mantenimiento del orden colectivo, sino también a la creación de hábitos de organización y respeto entre cada actor participante de la comunidad educativa, haciendo énfasis en los estudiantes, mujeres y hombres, por el proceso de aprendizaje. <br> <br> <b>Enfoque centrado en soluciones</b>: Busca resolver los problemas de la manera más rápida, eficiente y menos dolorosa, busca atacar el problema en el presente, en el “aquí y ahora”. <br> <br> <b>Enfoque de disciplina positiva</b>: Este enfoque educativo y parental que se centra en enseñar habilidades y comportamientos positivos, en lugar de castigar o reprimir los comportamientos negativos. Se basa en el respeto mutuo, la comunicación abierta y la enseñanza de habilidades sociales y emocionales. <br> <br> <b>Enfoque de factor de riesgos de la violencia</b>: Referente a la situación que incrementa las posibilidades de ser afectado por problemas que van a influir negativamente en el desarrollo normal de un individuo, un grupo o una comunidad. <br> <br> <b>Enfoque de protección de la violencia</b>: Es una habilidad o recurso que favorece el desarrollo humano, el mantenimiento o la recuperación de la salud y que permite a las personas, familias, escuelas o sociedad enfrentar con mayor eficacia situaciones de riesgo y; por lo tanto, reducir la vulnerabilidad. <br> <br>",
  52: "<b>Enfoque Psico-educacional</b>: Se centra en la labor que el profesional encargado de la gestión de los conflictos dentro de la unidad educativa, aplicando estrategias que promueven la gestión de las relaciones en el ámbito educativo, evitando centrarse únicamente en la conducta del estudiante y buscando preservar las relaciones entre estudiantes y maestras, maestros, dando la oportunidad de generar ambientes más positivos y donde los actores se hagan responsables de los roles que les corresponde. <br> <br>   <b>Enfoque restaurativo</b>: Entiende la dimensión humana de cada caso y brinda a las personas implicadas el espacio para transformar el conflicto y salir fortalecidas en valores y con habilidades para enfrentar nuevos retos. <br> <br>   <b>Enfoque sistémico</b>: Se considera a la familia y la escuela como sistemas que se relacionan entre sí de forma interdependiente. <br> <br>   <b>Facilitador de Prácticas Restaurativas</b>: Persona encargada de guiar y moderar los procesos restaurativos, asegurando un ambiente seguro y propicio para la resolución de conflictos. <br> <br>   <b>Justicia Restaurativa</b>: Tipo de justicia que surge de prácticas ancestrales, en la que se considera al delito como un daño a las relaciones sociales. En la medida de lo posible, involucra a la víctima, ofensor y comunidad para atender colectivamente los daños, necesidades y obligaciones derivados de la acción, con el propósito de sanar y generar reparación a las partes involucradas. <br> <br>   <b>La violencia escolar</b>: Incluye agresiones físicas (golpes, puñetazos, patadas), agresiones verbales (amenazas, burlas, apodos, rumores, entre otros), exclusión social, y además pueden presentarse agresiones sexuales (tocamientos no consentidos, relaciones sexuales forzadas). <br> <br>",
  53: "<b>Ofensor/a</b>: Persona que genera un daño individual o colectivo. <br> <br>  <b>Prácticas ancestrales</b>: Actividades propias de los pueblos o comunidades indígenas, que nacen de su cosmovisión y permiten comprender o dar respuesta a su realidad. <br> <br>   <b>Prácticas Restaurativas</b>: Son métodos y técnicas que aplican los principios de la justicia restaurativa en entornos educativos, con el objetivo de mejorar la convivencia y resolver conflictos. <br> <br>   <b>Reparación del Daño</b>: Implica identificar y abordar las consecuencias negativas de un conflicto, buscando restablecer la armonía y la confianza entre las personas afectadas. <br> <br>   <b>Señalética</b>: Técnica comunicacional que, mediante señales y símbolos icónicos, lingüísticos y cromáticos, orienta y brinda instrucción sobre cómo debe accionar una persona o un grupo de personas en un determinado espacio o ambiente físico. <br> <br>   <b>Víctima</b>: Persona que sufre un daño (físico, psicológico, material, etc.) ofensa (de palabra o acciones) por causas externas a su voluntad. <br> <br>   <b>Zona Restaurativa</b>: Es un espacio para una mayor coexistencia pacífica donde las autoridades, los ciudadanos y las instituciones públicas y privadas adoptan el enfoque de prácticas restaurativas como política social y lo aplican en todas sus acciones y relaciones de la vida cotidiana. <br> <br>",
  54: "<b>Albertí, M., & Pedrol, M. (2017)</b>. www.raco.cat. Obtenido de ´https://www.raco.cat <br> <br>  <b>Albertí i Cortés, M., & Pedrol Llirinós, M. (s.f.)</b>. El enfoque restaurativo en el ámbito educativo. Cuando innovar la escuela es humanizarla. Educació Social. Revista d’Intervenció Socioeducativa, 67, 47-72. <br> <br>   <b>Bisquerra, R., & Perez, N. (2007)</b>. Las competencias emocionales. Barcelona, España: Educación XXI. <br> <br>   <b>Bisquerra, R. (2011)</b>. Educación emocional: Propuestas para educadores y familia. Bilbao, España: Desclée de Brouwer, S.A. <br> <br>   <b>Canedo, A. (2014)</b>. Pasado, presente y futuro del periodismo. La Paz, Bolivia: Plural Editores. <br> <br>   <b>Diariodemediacion.es. (2018)</b>. Obtenido de https://www.diariodemediacion.es/diferencias-entre-justicia-restaurativa-y-practica-restaurativa/ <br> <br>   <b>Educación.gob.ec. (2018)</b>. Prácticas restaurativas en el ámbito educativo. Obtenido de https://educacion.gob.ec/practicas-restaurativas-en-el-ambito-educativo/ <br> <br>   <b>Educacionyfp.gob.es. (2020)</b>. Obtenido de https://www.educacionyfp.gob.es/mc/sgctie/convivencia-escolar/en-accion/practicas-restaurativas.html <br> <br>   <b>Eposgrado.com. (2019)</b>. Obtenido de https://www.epostgrado.com/practicas-restaurativas-otra-opcion-para-la-resolucion-de-conflictos-pacificas/´<br> <br>   <b>Estado Plurinacional de Bolivia; Ministerio de Educación. (2018)</b>. Protocolo de Prevención, Actuación y Denuncia en casos de violencia física, psicológica y sexual en Unidades Educativas y centros de Educación Especial. La Paz, Bolivia. <br> <br>",
  55: "<b>Fundacionesplai.org. (2023)</b>. Obtenido de ´https://fundacionesplai.org/blog/justicia-educativa/el-enfoque-de-la-justicia-restaurativa/´ <br> <br>  <b>García Montañez, M. V., & Ascensio Martínez, C. A. (2015)</b>. Bullying y violencia escolar: diferencias, similitudes, actores, consecuencias y origen. Revista Intercontinental de Psicología y Educación, 9-38. <br> <br>  <b>Gonzales, C. I. (2022)</b>. Obtenido de https://uvadoc.uva.es/bitstream/handle/10324/57806/TFG-O-2187.pdf <br> <br>  <b>Hopkins, B. (2020)</b>. Prácticas restaurativas en el aula. Palma, España: GOIB. <br> <br>  <b>Informe de 2013. (2016)</b>. Promover la justicia restaurativa para las niñas, niños y adolescentes. New York, Estados Unidos: Oficina del representante Especial del Secretario General sobre la violencia contra los niños. <br> <br>  <b>López, R. N. (2023)</b>. Fundación Esplai Restaurativa. Obtenido de https://fundacionesplai.org/blog/justicia-educativa/el-enfoque-de-la-justicia-restaurativa/ <br> <br>  <b>Maritza Garcia y Cristian Amaury. (2019)</b>. Universidad Intercontinental. Obtenido de https://www.uic.mx/bullying-violencia-escolar-diferencias-similitudes-actores-consecuencias-origen/ <br> <br>  <b>Matos Gamboa, J. (2012)</b>. Obtenido de www.eumed.net: https://www.eumed.net/rev/17/jmg.hmtl <br> <br>  <b>Paulero, R. (2021)</b>. Conflictos entre docentes y directivos de nivel primario. Representaciones, vivencias, comportamientos y consecuencias en la práctica docente. Revista Latinoamericana de Políticas y Administración de la Educación, 140-152. <br> <br>  <b>Progettomondo.Mlal, EDUCO, FUDEP. (2018)</b>. Prácticas Restaurativas para la prevención y gestión de conflictos en el ámbito educativo. La Paz, Bolivia: Imprenta Cerro Azul S.R.L. <br> <br>",
  56: "<b>Revista Pedagógos. (2013, mayo)</b>. El papel del alumno de ser activo. Obtenido de ´https://revista-pedagogos6.webnode.com.co/paulo-freire/su-pensamiento/´ <br> <br>   <b>Rodríguez, R. (2005)</b>. La acción tutorial para favorecer la convivencia: la disciplina. <br> <br>   <b>San Martín, J. A. (2003)</b>. La mediación escolar. Un camino para la gestión del conflicto escolar. Madrid, España. <br> <br>  <b>Schmitz, J. (2020)</b>. Prácticas restaurativas en el ámbito educativo. Ecuador. <br> <br>  <b>Terres des hommes. (2014)</b>. Auditoría Social de niños, niñas y adolescentes ¿Es tiempo de derechos? Cochabamba, Bolivia: Kipus. <br> <br>  <b>Trusco, D., & Inostroza, P. (2017, marzo)</b>. Las violencias en el espacio escolar. Naciones Unidas. <br> <br>  <b>UNEFCO. (2022)</b>. Ciclo: Promoviendo la convivencia pacífica y armónica en Unidades Educativas. Tarija, Bolivia: UNEFCO. <br> <br>  <b>UNICEF. Santander, F. (2019)</b>. Estrategia Nacional de Prevención de la Violencia contra Niñas, Niños, Adolescentes y Mujeres. La Paz, Bolivia: Viceministerio de Seguridad Ciudadana. <br> <br> <b>Vargas, G. (2019)</b>. Factores protectores y afrontamiento de riesgos asociados al uso de sustancias psicoactivas en adolescentes y jóvenes. La Paz, Bolivia: WA-GUI. <br> <br>  <b>Zehr, H. (2007, julio)</b>. Obtenido de https://www.icbf.gov.co/sites/default/files/el_pequeno_libro_de_las_justicia_restaurativa.pdf <br> <br>  <b>Zimmermann, A. (2000)</b>. Gestión de cambio organizacional. Caminos y herramientas. Ecuador: Ediciones Abya-Yala. <br> <br>",
  57: " ",
  
  //   14: "13Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc,",
};
const titlesData = {
  0: "texto0",
  1: "De la justicia restaurativa a las prácticas educativas",
  2: "CONTENIDO",
  3: "Presentación",
  4: "DATOS GENERALES DEL CUADERNO",
  5: " ",
  6: "Qué conocemos sobre prácticas restaurativas",
  7: "Justicia restaurativa",
  8: "Aspectos fundamentales de la justicia restaurativa en la unidad educativa",
  9: "Principios básicos de la Justicia Restaurativa",
  10: "Concepto del daño o falta u ofensa, falta u ofensa individual o colectiva.",
  11: "La violencia escolar",
  12: "Manifestación de la violencia escolar",
  13: "Tipos de la violencia en el sistema educativo",
  14: ["El bullying, acoso escolar", "Formas que adquiere el acoso escolar o bullying "],
  15: ["El bullying o acoso escolar en la actualidad", "Características del bullying o acoso escolar "],
  16: "Necesidades que se generan a partir por delito o falta",
  17: "Consecuencias emocionales por agresión",
  18: ["El aporte de la justicia restaurativa a la práctica restaurativa escolar", "Justicia Restaurativa y su Impacto en la Comunidad Educativa"],
  19: "Práctica Restaurativa en la Educación",
  20: "Prácticas restaurativas no formales",
  21: "Aplicación de principios del enfoque restaurativo ",
  22: " ",
  23: "Comunidad restaurativa",
  24: "Hacia una Comunidad Restaurativa:",
  25: "Las bases de una comunidad educativa restaurativa",
  26: "Maestras y maestros como facilitadores de las prácticas restaurativas",
  27: "Las prácticas restaurativas ofrecen un marco teórico y práctico",
  28: "Para la prevención",
  29: "Para la resolución de conflictos",
  30: "Consejo educativo en la prevención de conflictos",
  31: "Estudiantes como protagonistas de las prácticas restaurativas",
  32: ["Estrategia de Prevención", "El Rol del Estudiante en la Prevención de la Violencia"],
  33: ["Resolución de Conflictos", "Desarrollo de Habilidades para una Convivencia Pacífica"],
  34: "Participación restaurativa de madre, padre o tutor de familia",
  35: "Análisis de caso",
  36: " ",
  37: "Historia de una situación de conflicto",
  38: ["Finalidades en el desarrollo de las prácticas restaurativas","prácticas restaurativas novedosas"],
  39: "Concepto y características de una zona restaurativa",
  40: "Definimos el rol de los integrantes de la comunidad educativa en una zona restaurativa.",
  41: "Actividades con enfoque restaurativo",
  42: "Planes de convivencia pacífica",
  43: " ",
  44: "Vivencia de las prácticas restaurativas",
  45: "Prácticas restaurativas en las comunidades educativas ",
  46: "Señalética con mensajes restaurativos en la unidad educativa",
  47: "Beneficios de una zona educativa restaurativa",
  48: "Análisis de caso",
  49: "Consignas de aplicación",
  50: "Glosario",
  51: "Glosario",
  52: "Glosario",
  53: "Glosario",
  54: "Glosario",
  55: "Bibliografia",
  56: "Bibliografia",
  57: "Bibliografia",
  //58: " ",
};


const layoutData = {
  0: "Alayout",
  1: "Blayout",
  2: "Clayout",
  3: "Blayout",
  4: "Dlayout",
  5: "Elayout",
  6: "Flayout",
  7: "Klayout",
  8: "Jlayout",
  9: "Blayout",
  10: "Dlayout",
  11: "Jlayout",
  12: "Dlayout",
  13: "Jlayout",
  14: "Glayout",
  15: "Glayout",
  16: "Blayout",
  17: "Jlayout",
  18: "Glayout",
  19: "Blayout",
  20: "Jlayout",
  21: "Flayout",
  22: "Elayout",
  23: "Flayout",
  24: "Klayout",
  25: "Jlayout",
  26: "Dlayout",
  27: "Jlayout",
  28: "Dlayout",
  29: "Klayout",
  30: "Dlayout",
  31: "Jlayout",
  32: "Glayout",
  33: "Glayout",
  34: "Dlayout",
  35: "Flayout",
  36: "Elayout",
  37: "Flayout",
  38: "Glayout",
  39: "Jlayout",
  40: "Llayout",
  41: "Dlayout",
  42: "Jlayout",
  43: "Ilayout",
  44: "Blayout",
  45: "Blayout",
  46: "Jlayout",
  47: "Dlayout",
  48: "Flayout",
  49: "Mlayout",
  50: "Blayout",
  51: "Blayout",
  52: "Blayout",
  53: "Blayout",
  54: "Blayout",
  55: "Blayout",
  56: "Blayout",
  57: "Blayout",
  //58: "Alayout",
    
};

const popUpData = {
  0: " ",
  1: "",
  2: "",
  3: "",
  4: [
      {
        title: "T ",
        typeofContent: "image",
        contentModal: "PAG4POP-1.png",
        buttonName: "+",
      },
     // {
       // title: "Titulo del modal1111DDD",
        //typeofContent: "text",
        //contentModal:
          //"tezto a remplazar",
       // buttonName: "+",
     // },
    ],
  5: "",
  6: "",
  7: "",
  8: "",
  9: "",
  10:  [
    {
      title: " ",
      typeofContent: "text",
      contentModal: "Las prácticas restaurativas en el ámbito educativo abordan los conflictos desde un enfoque social, afectivo, pedagógico y de derechos, orientado por los principios de protección integral e interés superior de niñas, niños y adolescentes, mujeres y hombres. Diferentes investigaciones  prueban que el modelo de gestión de conflictos basado en el enfoque restaurativo frena la reincidencia, facilita la restauración de relaciones entre las personas implicadas, ayuda a instaurar un sentimiento de pertenencia a la comunidad, favorece la reparación de los daños, faltas u ofensas en el grupo de estudiantes víctimas y aumenta la implicación personal en la resolución.",
      buttonName: "+",
    },
    {
      title: " ",
      typeofContent: "text",
      contentModal:
        "En la comunidad educativa las prácticas restaurativas están dirigidas a crear y fortalecer el sentido de comunidad y prevenir, detectar y gestionar los conflictos y las manifestaciones de violencia. Las herramientas principales que utiliza el enfoque restaurativo son la escucha activa, el diálogorestaurativo, la Comunicación No Violenta, y los círculos restaurativos. Implementadas de manera progresiva y constante, las prácticas restaurativas ayudan a disminuir la deserción escolar y a mejorar el rendimiento académico de los estudiantes. (educación.gob.ec, 2018)",
      buttonName: "+",
    },
    ],
  11: "",
  12:  [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG12POP-1.png",
      buttonName: "+",
    },
    //{
    //  title: "Titulo del modal1111DDD",
    //  typeofContent: "text",
   //   contentModal:
    //    "tezto a remplazar",
   //   buttonName: "+",
  //  },
    ],
  13: "",
  14: [
      {
        title: "",
        typeofContent: "image",
        contentModal:
          "PAG14POP-1.png",
        buttonName: "Manifestación del bullying",
      },
    ],
  15: [
    {
      title: "",
      typeofContent: "image",
      contentModal:
        "PAG15POP-1.png",
      buttonName: "Internet y Bullying",
    },
    ],
  16: "",
  17: "",
  18: [
    {
      title: "",
      typeofContent: "text",
      contentModal:
        "En las comunidades educativas o en la unidad educativa, las prácticas restaurativas están dirigidas a crear y fortalecer el sentido de comunidad y prevenir, detectar y gestionar los conflictos y las manifestaciones de violencia. Las herramientas principales que utiliza el enfoque restaurativo son la escucha activa, el diálogo restaurativo, la comunicación no violenta y los círculos restaurativos. Los cuales son Implementados de manera progresiva y constante, las prácticas restaurativas, en general, ayudan a disminuir la deserción escolar y a mejorar el rendimiento académico del estamento estudiantil. (educación.gob.ec, 2018)",
      buttonName: "Fortalecer sentido de comunidad",
    },
    ],
  19: "",
  20: "",
  21: "",
  22: "",
  23: "",
  24: "",
  25: "",
  26:  [
    //{
     // title: "Titulo del modal000DDD",
      //typeofContent: "image",
      //contentModal: "layOutD.jpg",
      //buttonName: "+",
    //},
    {
      title: " ",
      typeofContent: "text",
      contentModal:
        "Las prácticas restaurativas en el ámbito educativo se basan en el desarrollo de la comunidad a partir del fortalecimiento de los vínculos. Cuando se dan conflictos en la vida del centro, lo que se busca es la reparación de los daño o falta u ofensas causados asumiendo responsabilidades. (Gonzales, 2022)",
      buttonName: "+",
    },
    ],
  27: "",
  28:  [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG28POP-1.png",
      buttonName: "+",
    },
  //{
    //  title: "Titulo del modal1111DDD",
    //  typeofContent: "text",
   //   contentModal:
    //    "tezto a remplazar",
   //   buttonName: "+",
  //  },
    ],
  29: "",
  30:  [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG30POP-1.png",
      buttonName: "+",
    },
  //{
    //  title: "Titulo del modal1111DDD",
    //  typeofContent: "text",
   //   contentModal:
    //    "tezto a remplazar",
   //   buttonName: "+",
  //  },
    ],
  31: "",
  32: [
    {
      title: "",
      typeofContent: "text",
      contentModal:
        "El estudiante, mujer u hombre, al ser consciente sobre que cada conducta tiene su efecto de manera directa e indirecta, tomando en cuenta que toda acción tiene una reacción, tendrá la posibilidad de reflexionar, analizar o evitar ciertas conductas o comportamientos que dañen a otra persona; por lo tanto, ayudarán, de una u otra manera, a los procesos de prevención de diferentes faltas y/o infracciones, de violencias hacia uno mismo, como también hacia su entorno. Se convierten en los protagonistas que pueden ir coadyuvando en las prácticas restaurativas y fortalecer a los gobiernos estudiantes que permita tener una mejor y mayor representación de la población de estudiantes de la unidad educativa.",
      buttonName: "Estudiante consciente",
    },
    ],
  33: [
    {
      title: "",
      typeofContent: "image",
      contentModal:
      "PAG33POP-1.png",
      buttonName: "Prevención de conflictos estudiantiles",
    },
    ],
  34:  [
    {
      title: "Para la prevención de conflictos y violencia",
      typeofContent: "text",
      contentModal: " La inclusión activa de madre/padre o tutor de familia en la prevención del conflicto a través de la resolución de los mismos no es solo el de brindar la información sobre los desafíos o los problemas que se puede atravesar en la unidad educativa sino y, sobre todo, el de su involucramiento como partícipes, como socios en una búsqueda de soluciones conjuntas y sobre todo de la comunitarias. La conexión estrecha entre la comunidad educativa y las familias promueve una cultura de cooperación que beneficia no solo a la resolución de conflictos individuales, a los colectivos y sobre todo al ambiente educativo en su conjunto (Fernández M. , 2009).",
      buttonName: "+",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal:
        "PAG34POP-1.png",
      buttonName: "+",
    },
    ],
  35: "",
  36: "",
  37: "",
  38:  [
    {
      title: " ",
      typeofContent: "image",
      contentModal:
        "PAG38POP-1.png",
      buttonName: "Zona restaurativa",
    },
    ],
  39: "",
  40:   [
       {
    title: " ",
    typeofContent: "text",
    contentModal: "Que es uno de los beneficiarios de la intervención, en quien se busca generar conciencia sobre la restitución de derecho afectado, la responsabilidad sobre la ofensa cometida, la reparación del daño a la víctima y la reintegración a la comunidad educativa para cambiar su trayectoria.",
    buttonName: "El niño, niña, adolescente o persona adulta ofensora",
      },
      {
        title: " ",
        typeofContent: "text",
        contentModal: " Que es el otro beneficiario de la intervención, en quien se busca generar conciencia sobre su situación, la necesidad de reparación y la generación de confianza para poder reencontrarse con la persona que ha generado la ofensa, la falta o el daño y reintegrarse a su comunidad educativa luego del daño del que fue objeto.",
        buttonName: "El niño, niña, adolescente o persona adulta víctima",
          },
          {
            title: " ",
            typeofContent: "text",
            contentModal: "A la que se reintegra la persona que actúo como ofensor/a y persona que resultó víctima. También puede ser sujeto o espacio de reparación y, al mismo tiempo, responsable de la ejecución de acciones para mejorar la convivencia escolar.",             buttonName: "La comunidad educativa",
              },
              {
                title: " ",
                typeofContent: "text",
                contentModal: "Que tiene el perfil y la preparación adecuada para la conducción de las prácticas restaurativas; en general maestras y maestros.", 
                buttonName: "Facilitadores de la práctica",
                  },
                  {
                    title: " ",
                    typeofContent: "text",
                    contentModal: "Integrantes de la comunidad educativa que pueden ser el personal de dirección, maestras, maestros o una persona encargada de realizar el proceso restaurativo al interior de la unidad educativa, entre otros.",                     buttonName: "Las autoridades de gestión y dirección",
                      },
    ],
  41:  [
    {
      title: " ",
      typeofContent: "text",
      contentModal: "Este abordaje debe ser incluido en la planificación educativa de las y los maestros, considerando los siguientes instrumentos de gestión, según corresponda el nivel educativo en el sistema: <br> <br> • Plan de desarrollo curricular (PDC) <br> • Proyecto Socio Comunitario Productivo (PSP) <br> • Plan de Anual Trimestralizado (PAT)",
      buttonName: "+",
    },
    {
      title: " ",
      typeofContent: "text",
      contentModal:
        "a. Los <b>derechos y deberes</b> de las y los miembros de la <b>comunidad educativa</b> y/o centros. <br> <br> b. <b>Normas de conducta</b> favorables a la <b>convivencia pacífica y armónica</b>, el <b>buen trato</b> de la comunidad educativa. <br> <br> c. El <b>procedimiento disciplinario</b> que describa detalladamente las conductas que vulneran las <b>normas de convivencia</b>. <br> <br> d. La descripción de las <b>sanciones internas</b> que definan las unidades educativas y/o centros, sean públicas, privadas o de convenio. <br> <br> e. El <b>procedimiento marco</b> para la adopción de decisiones disciplinarias que deben sujetarse a <b>criterios y valores</b> conocidos por normas educativas nacionales, departamentales, municipales y de la región, evitando de toda forma las <b>decisiones arbitrarias</b>. <br> <br> f. La descripción de <b>procedimientos alternativos</b> para la resolución de conflictos, si la comunidad así lo establece, siempre que no sean contrarios a ninguna norma. <br> <br> g. La <b>remisión de informes anuales</b> sobre los casos de <b>acoso, violencia y/o abusos</b> a través de las instancias correspondientes de la red educativa, Distrital de Educación, Departamental de Educación hasta llegar al <b>Ministerio de Educación</b>. <br> <br> h. La organización de <b>programas y talleres de capacitación</b> destinados a la <b>prevención</b>. <br> <br> i. La programación de <b>actividades</b>, con el fin exclusivo de fomentar un clima de <b>convivencia pacífica y armónica</b> dentro de las unidades educativas y/o centros. <br> <br> ",
      buttonName: "+",
    },
    ],
  42: "",
  43: "",
  44: "",
  45: "",
  46: "",
  47:  [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG47POP-1.png",
      buttonName: "+",
    },
    {
      title: " ",
      typeofContent: "text",
      contentModal:
        "tPAG47POP-2.png",
      buttonName: "+",
    },
    ],
  48: "",
  49: "",
  50: "",
  51: "",
  52: "",
  53: "",
  54: "",
  55: "",
  56: "",
  57: "",
  58: "",
  };
const imagesData = {
  0: " ",
  1: "",
  2: "",
  3: "",
  4: "PAG4-1.png",
  5: "PAG5-1.png",
  6: ["PAG6-1.png", "PAG6-2.png"],
  7: "PAG7-1.png",
  8: ["PAG8-1.png", "PAG8-2.png", "PAG8-3.png", "PAG8-4.png", "PAG8-5.png"],
  9: "",
  10: "PAG7-1.png",
  11: ["PAG11-1.png", "PAG11-2.png", "PAG11-3.png", "PAG11-4.png", "PAG11-5.png"],
  12: "PAG12-1.png",
  13: ["PAG13-1.png", "PAG13-2.png", "PAG13-3.png", "PAG13-4.png", "PAG13-5.png"],
  14: "",
  15: "",
  16: "",
  17: ["PAG17-1.png", "PAG17-2.png", "PAG17-3.png", "PAG17-4.png", "PAG17-5.png"],
  18: "",
  19: "",
  20: ["PAG20-1.png", "PAG20-2.png", "PAG20-3.png", "PAG20-4.png", "PAG20-5.png"],
  21: ["PAG21-1.png", "PAG21-2.png"],
  22: "PAG22-1.png",
  23: ["PAG23-1.png", "PAG23-2.png"],
  24: "PAG24-1.png",
  25: ["PAG25-1.png", "PAG25-2.png", "PAG25-3.png", "PAG25-4.png", "PAG25-5.png"],
  26: "PAG26-1.png",
  27: ["PAG27-1.png", "PAG27-2.png", "PAG27-3.png", "PAG27-4.png", "PAG27-5.png"],
  28: "PAG28-1.png",
  29: "PAG29-1.png",
  30: "PAG30-1.png",
  31: ["PAG31-1.png", "PAG31-2.png", "PAG31-3.png", "PAG31-4.png", "PAG31-5.png"],
  32: "",
  33: "",
  34: "PAG34-1.png",
  35: ["PAG35-1.png", "PAG35-2.png"],
  36: "PAG36-1.png",
  37: ["PAG37-1.png", "PAG37-2.png"],
  38: "",
  39: ["PAG39-1.png", "PAG39-2.png", "PAG39-3.png", "PAG39-4.png", "PAG39-5.png"],
  40: "",
  41: "PAG41-1.png",
  42: ["PAG42-1.png", "PAG42-2.png", "PAG42-3.png", "PAG42-4.png", "PAG42-5.png"],
  43: ["PAG43-1.png", "PAG43-2.png"],
  44: "",
  45: "",
  46: ["PAG46-1.png", "PAG46-2.png", "PAG46-3.png", "PAG46-4.png", "PAG46-5.png"],
  47: "PAG47-1.png",
  48: ["PAG48-1.png", "PAG48-2.png"],
  49: "",
  50: "PAG50-1.png",
  51: "",
  52: "",
  53: "",
  54: "",
  55: "",
  56: "",
  57: "",
  58: "",

};

const buttonsNameData = {
  0: "",
  1: "",
  2: "",
  3: "",
  4: "",
  5: [ "Aspectos fundamentales de la Justicia Restaurativa en la unidad educativa", "Tipos de la violencia en el sistema educativo","Consecuencias emocionales por agresión","El aporte de la Justicia restaurativa a la práctica restaurativa escolar"
  ],
  6: "",
  7: "",
  8: "",
  9: "",
  10: "",
  11: "",
  12: "",
  13: "",
  14: "",
  15: "",
  16: "",
  17: "",
  18: "",
  19: "",
  20: "",
  21: "",
  22: [
    "Las bases de una comunidad educativa restaurativa","Maestras y maestros como facilitadores de las prácticas restaurativas"," Consejo Educativo en la prevención de conflictos.","Estudiantes como protagonistas de las prácticas restaurativas"

  ],
  23: "",
  24: "",
  25: "",
  26: "",
  // 27: "",
  27: "",
  28: "",
  29: "",
  30: "",
  31: "",
  32: "",
  33: "",
  34: "",
  35: "",
  36: [ "Concepto y características de una zona restaurativa","El rol de los integrantes de la comunidad educativa en una zona restaurativa","Actividades con enfoque restaurativo","Beneficios de una zona educativa restaurativa"

  ],
  37: "",
  38: "",
  39: "",
  40: "",
  41: "",
  42: "",
  43: "",
  44: "",
  45: "",
  46: "",
  47: "",
  48: "",
  49: ["Información","Interpretación","Conclusiones", "Estrategias" ],
  50: "",
  51: "",
  52: "",
  53: "",
  54: "",
  55: "",
  56: "",
  57: "",
  58: "",
};

const buttonsPageNumberData = {
  0: "",
  1: "",
  2: "",
  3: "",
  4: "",
  5: [8, 13, 17, 18 ],
  6: "",
  7: "",
  8: "",
  9: "",
  10: "",
  11: "",
  12: "", 
  13: "",
  14: "",
  15: "",
  16: "",
  17: "",
  18: "",
  19: "",
  20: "",
  21: "",
  22: [25, 26, 30, 31 ],
  23: "",
  24: "",
  25: "",
  26: "",
  27: "",
  27: "",
  28: "",
  29: "",
  30: "",
  31: "",
  32: "",
  33: "",
  34: "",
  35: "",
  36: [39, 40, 41, 47],
  37: "",
  38: "",
  39: "",
  40: "",
  41: "",
  42: "",
  43: "",
  44: "",
  45: "",
  46: "",
  47: "",
  48: "",
  49: "",
  50: "",
  51: "",
  52: "",
  53: "",
  54: "",
  55: "",
  56: "",
  57: "",
  58: "",
  
};
const linksData = {
  0: "",
  1: "",
  2: "",
  3: "",
  4: "",
  5: "",
  6: "",
  7: "",
  8: "",
  9: "",
  10: "",
  11: "",
  12: "",
  13: "",
  14: "",
  15: "",
  16: "",
  17: "",
  18: "",
  19: "",
  20: "",
  21: "",
  22: "",
  23: "",
  24: "",
  25: "",
  26: "",
  27: "",
  27: "",
  28: "",
  29: "",
  30: "",
  31: "",
  32: "",
  33: "",
  34: "",
  35: "",
  36: "",
  37: "",
  38: "",
  39: "",
  40: "",
  41: "",
  42: "",
  43: "",
  44: "",
  45: "",
  46: "",
  47: "",
  48: "",
  49: "",
  50: "",
  51: "",
  52: "",
  53: "",
  54: "",
  55: "",
  56: "",
  57: "",
 // 58: "",
};
